import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { Banknote, CreditCard, Minus, Plus, Printer, Receipt, Search, ShoppingCart, Trash2, WalletCards, X } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { toast, Toaster } from "sonner";
import MorrowLogo from "../components/branding/MorrowLogo";
import CashierReceipt, { printCashierReceipt, type CashierReceiptData } from "../components/cashier/CashierReceipt";
import { useCashierOrders } from "../hooks/useRealtimeOrders";
import { createOrder } from "../services/supabase/orderService";
import { useAuth } from "../auth/AuthContext";
import { loadMenu } from "../services/supabase/menuService";
import type { NormalizedMenuProduct } from "../services/supabase/menuModels";

type CashierMenuProduct = NormalizedMenuProduct & { cashierCategory: string; needsConfiguration: boolean };

type PaymentMethod = "Cash" | "Card";
type CashierOrderItem = { id: string; productId: string; name: string; image: string; category: string; unitPrice: number; quantity: number; customizations: string[]; customizationOptionIds: string[] };
type CashierOrder = { id: string; time: string; total: number; paymentMethod: PaymentMethod; status: "Completed"; items: CashierOrderItem[]; receipt: CashierReceiptData };
type ShiftSummary = { totalSales: number; completedOrders: number; cashTotal: number; cardTotal: number };
type Tool = "orders" | "receipts" | "shift";

const CURRENCY = new Intl.NumberFormat("en-IE", { style: "currency", currency: "EUR" });
const TAX_RATE = 0.08;
const button = "cashier-button rounded-xl px-4 py-2.5 text-sm font-bold focus:outline-none focus-visible:ring-2 focus-visible:ring-[#d7fb69]/50 disabled:cursor-not-allowed disabled:opacity-35";
function categoryPlaceholder(category:string){const label=category||"Food";const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 280"><rect width="640" height="280" fill="#151a15"/><circle cx="320" cy="118" r="54" fill="#d7fb69" fill-opacity=".12"/><path d="M285 126h70M299 103h42M303 149h34" stroke="#d7fb69" stroke-width="10" stroke-linecap="round"/><text x="320" y="226" fill="#f5f5ef" fill-opacity=".55" font-family="Arial,sans-serif" font-size="24" text-anchor="middle">${label}</text></svg>`;return `data:image/svg+xml,${encodeURIComponent(svg)}`;}

function Modal({ title, children, onClose, wide=false }: { title: string; children: ReactNode; onClose: () => void; wide?: boolean }) {
  return <div className="fixed inset-0 z-[10000] flex items-center justify-center bg-black/75 p-4 backdrop-blur-[2px]" role="dialog" aria-modal="true" aria-label={title} onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><div className={`cashier-dialog max-h-[90vh] w-full overflow-y-auto rounded-[20px] p-6 ${wide?"max-w-3xl":"max-w-md"}`}><div className="mb-6 flex items-center"><h2 className="text-lg font-black tracking-[-.025em]">{title}</h2><button aria-label="Close" onClick={onClose} className="ml-auto rounded-xl p-2 text-white/45 transition-colors hover:bg-white/10 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#d7fb69]/45"><X size={18}/></button></div>{children}</div></div>;
}

function ProductImage({ product, className }: { product: CashierMenuProduct; className: string }) {
  return <img src={product.image||categoryPlaceholder(product.cashierCategory)} alt={product.name} className={className} onError={event => { const image=event.currentTarget;if(image.dataset.fallbackApplied==="true")return;image.dataset.fallbackApplied="true";image.src=categoryPlaceholder(product.cashierCategory); }}/>
}

export default function CashierDashboard() {
  const liveOrders=useCashierOrders();
  const { profile }=useAuth();
  const [orderItems,setOrderItems]=useState<CashierOrderItem[]>([]);
  const [search,setSearch]=useState("");
  const [category,setCategory]=useState("All");
  const [registerOpen,setRegisterOpen]=useState(true);
  const [tool,setTool]=useState<Tool|null>(null);
  const [customizing,setCustomizing]=useState<CashierMenuProduct|null>(null);
  const [selections,setSelections]=useState<Record<string,string>>({});
  const [clearConfirm,setClearConfirm]=useState(false);
  const [closeConfirm,setCloseConfirm]=useState(false);
  const [cashOpen,setCashOpen]=useState(false);
  const [received,setReceived]=useState("");
  const [recentOrders,setRecentOrders]=useState<CashierOrder[]>([]);
  const [selectedOrder,setSelectedOrder]=useState<CashierOrder|null>(null);
  const [completedReceipt,setCompletedReceipt]=useState<CashierReceiptData|null>(null);
  const [submitting,setSubmitting]=useState(false);
  const [menuProducts,setMenuProducts]=useState<CashierMenuProduct[]>([]);
  const [menuCategories,setMenuCategories]=useState<string[]>([]);
  const [menuLoading,setMenuLoading]=useState(true);
  const [idempotencyKey,setIdempotencyKey]=useState(()=>crypto.randomUUID());
  const searchRef=useRef<HTMLInputElement>(null);

  useEffect(()=>{let active=true;setMenuLoading(true);void loadMenu({force:true}).then(result=>{if(!active)return;if(result.ok){const names=new Map(result.data.categories.map(item=>[item.slug,item.name]));setMenuCategories(result.data.categories.map(item=>item.name));setMenuProducts(result.data.products.map(product=>({...product,cashierCategory:names.get(product.category.replace(/_/g,"-"))??product.category,needsConfiguration:false})));}else toast.error(result.error.message);}).finally(()=>{if(active)setMenuLoading(false);});return()=>{active=false;};},[]);
  const categories=useMemo(()=>["All",...menuCategories],[menuCategories]);
  const visibleProducts=useMemo(()=>{const query=search.trim().toLowerCase();return menuProducts.filter(product=>(product.needsConfiguration||product.available&&product.inStock)&&(category==="All"||product.cashierCategory===category)&&(!query||product.name.toLowerCase().includes(query)||product.cashierCategory.toLowerCase().includes(query)||product.keywords.some(keyword=>keyword.includes(query))));},[category,search,menuProducts]);
  const subtotal=orderItems.reduce((sum,item)=>sum+item.unitPrice*item.quantity,0);
  const tax=subtotal*TAX_RATE;
  const total=subtotal+tax;
  const shift:ShiftSummary=recentOrders.reduce((summary,order)=>({totalSales:summary.totalSales+order.total,completedOrders:summary.completedOrders+1,cashTotal:summary.cashTotal+(order.paymentMethod==="Cash"?order.total:0),cardTotal:summary.cardTotal+(order.paymentMethod==="Card"?order.total:0)}),{totalSales:0,completedOrders:0,cashTotal:0,cardTotal:0});
  const amountReceived=Number(received)||0;
  const change=Math.max(0,amountReceived-total);

  useEffect(()=>{const shortcut=(event:KeyboardEvent)=>{if(event.key==="/"&&!event.ctrlKey&&!event.metaKey){const target=event.target as HTMLElement;if(!["INPUT","TEXTAREA"].includes(target.tagName)){event.preventDefault();searchRef.current?.focus();}}if(event.key==="Escape"&&document.activeElement===searchRef.current)setSearch("");};window.addEventListener("keydown",shortcut);return()=>window.removeEventListener("keydown",shortcut);},[]);

  const addConfigured=(product:CashierMenuProduct, chosen:Record<string,string>={})=>{const chosenOptions=product.customizationGroups.flatMap(group=>group.options.filter(option=>chosen[group.id]===option.id));const names=chosenOptions.map(option=>option.name);const customizationOptionIds=chosenOptions.map(option=>option.databaseId??option.id);const unitPrice=product.price+chosenOptions.reduce((sum,option)=>sum+option.priceAdjustment,0);const id=[product.id,...Object.entries(chosen).sort().map(([,value])=>value)].join("::");setOrderItems(current=>current.some(item=>item.id===id)?current.map(item=>item.id===id?{...item,quantity:item.quantity+1}:item):[...current,{id,productId:product.id,name:product.name,image:product.image,category:product.cashierCategory,unitPrice,quantity:1,customizations:names,customizationOptionIds}]);toast.success(`${product.name} added`,{duration:1200});setCustomizing(null);setSelections({});};
  const chooseProduct=(product:CashierMenuProduct)=>{if(product.needsConfiguration||!product.available||!product.inStock)return;const groups=product.customizationGroups.filter(group=>group.required);if(!groups.length){addConfigured(product);return;}const defaults=Object.fromEntries(groups.map(group=>[group.id,group.options.find(option=>option.default)?.id??""]));setSelections(defaults);setCustomizing(product);};
  const confirmCustomization=()=>{if(!customizing)return;const required=customizing.customizationGroups.filter(group=>group.required);if(required.some(group=>!selections[group.id])){toast.error("Choose all required options.");return;}addConfigured(customizing,selections);};
  const updateQuantity=(id:string,quantity:number)=>setOrderItems(current=>quantity<1?current.filter(item=>item.id!==id):current.map(item=>item.id===id?{...item,quantity}:item));
  const completeSale=async()=>{
    if(submitting)return;
    if(amountReceived<total){toast.error("Amount received is less than the total due.");return;}
    setSubmitting(true);
    const result=await createOrder({
      items:orderItems.map(item=>({id:item.id,productId:item.productId,qty:item.quantity,price:item.unitPrice,customizationOptionIds:item.customizationOptionIds})),
      orderType:"dine_in",
      idempotencyKey,
      source:"cashier",
      branchId:profile?.branch_id??undefined,
    });
    setSubmitting(false);
    if(!result.ok){
      console.error("[MORROW] Cashier createOrder failed:",result.error);
      toast.error(result.error.message);
      return;
    }
    const now=new Date();
    const authoritativeSubtotal=Number(result.data.subtotal);
    const authoritativeTax=Number(result.data.tax);
    const authoritativeTotal=Number(result.data.total);
    const authoritativeChange=Math.max(0,amountReceived-authoritativeTotal);
    const id=result.data.order_number;
    const receipt:CashierReceiptData={orderNumber:id,date:now.toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"}),cashierName:profile?.full_name??"Cashier",restaurantName:"Morrow Restaurant",branchName:"Main Branch",registerName:"Cashier Register",items:orderItems.map(item=>({id:item.id,name:item.name,quantity:item.quantity,unitPrice:item.unitPrice,lineTotal:item.unitPrice*item.quantity,customizations:[...item.customizations]})),subtotal:authoritativeSubtotal,taxRate:authoritativeSubtotal?authoritativeTax/authoritativeSubtotal:TAX_RATE,taxAmount:authoritativeTax,total:authoritativeTotal,paymentMethod:"cash",amountReceived,change:authoritativeChange};
    const order:CashierOrder={id,time:now.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),total:authoritativeTotal,paymentMethod:"Cash",status:"Completed",items:orderItems.map(item=>({...item,customizations:[...item.customizations],customizationOptionIds:[...item.customizationOptionIds]})),receipt};
    setRecentOrders(current=>[order,...current]);
    setCompletedReceipt(receipt);
    setOrderItems([]);
    setCashOpen(false);
    setReceived("");
    setIdempotencyKey(crypto.randomUUID());
    toast.success(`Sale completed · ${order.id} · Change ${CURRENCY.format(authoritativeChange)}`);
  };
  const printReceipt=(receipt:CashierReceiptData)=>{if(!printCashierReceipt(receipt))toast.error("Printing was blocked. Allow popups and try again.");};

  return <main className="morrow-cashier flex min-h-screen flex-col bg-[#0b0d0a] font-['DM_Sans'] text-white"><Toaster theme="dark" position="top-right"/>
    <header className="flex items-center justify-between border-b border-white/[.06] bg-[#0d0f0c] px-4 py-4 sm:px-6"><div><MorrowLogo variant="full" priority className="h-auto w-36"/><p className="mt-1 text-xs text-white/40">Register · Main Branch · Current shift</p><p className="mt-1 text-[10px] text-white/30">{liveOrders.isDemo?"Demo orders":`${liveOrders.orders.length} branch orders · ${liveOrders.connection}`}</p></div><button onClick={()=>registerOpen?setCloseConfirm(true):setRegisterOpen(true)} className={`cashier-button rounded-xl border px-4 py-2 text-xs font-bold ${registerOpen?"border-emerald-500/20 bg-emerald-500/10 text-emerald-400":"border-red-500/20 bg-red-500/10 text-red-400"}`}>{registerOpen?"Close Register":"Open Register"}</button></header>
    <div className="grid min-h-0 flex-1 lg:grid-cols-[minmax(0,1fr)_400px]"><section className="min-w-0 p-4 sm:p-6"><div className="relative"><Search size={18} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-white/40"/><input ref={searchRef} value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search menu..." className="cashier-search h-12 w-full rounded-2xl pl-12 pr-20 text-sm outline-none"/>{!search&&<kbd className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 rounded-md border border-white/10 bg-white/[.04] px-2 py-1 text-[10px] font-bold text-white/35">/</kbd>}{search&&<button aria-label="Clear search" onClick={()=>{setSearch("");searchRef.current?.focus();}} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-2 text-white/40 transition-colors hover:bg-white/10 hover:text-white"><X size={16}/></button>}</div>
      <div className="my-4 flex gap-2.5 overflow-x-auto pb-1" aria-label="Menu categories">{categories.map(label=><button key={label} onClick={()=>setCategory(label)} className={`cashier-category min-h-10 shrink-0 rounded-xl border px-4 text-sm font-bold focus:outline-none focus-visible:ring-2 focus-visible:ring-[#d7fb69]/40 ${category===label?"border-[#d7fb69] bg-[#d7fb69] text-[#17200f]":"border-white/[.08] bg-[#141614] text-white/58 hover:border-white/20 hover:text-white"}`}>{label}</button>)}</div>
      {menuLoading?<div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{Array.from({length:8},(_,index)=><div key={index} className="cashier-skeleton min-h-52 rounded-[18px]"/>)}</div>:visibleProducts.length===0?<div className="grid min-h-52 place-items-center rounded-[18px] border border-dashed border-white/10 bg-[#141614]/60 text-center"><div><Search size={24} className="mx-auto mb-3 text-white/20"/><p className="text-sm font-bold text-white/60">No menu items found</p><p className="mt-1 text-xs text-white/35">Try another search or category.</p></div></div>:<div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{visibleProducts.map(product=><button key={product.id} disabled={!registerOpen||product.needsConfiguration||!product.available||!product.inStock} onClick={()=>chooseProduct(product)} className="cashier-product group relative min-h-52 overflow-hidden rounded-[18px] text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-[#d7fb69]/55 disabled:opacity-40"><span aria-hidden="true" className="cashier-product-add absolute right-3 top-3 z-10 grid size-9 place-items-center rounded-full bg-[#d7fb69] text-[#17200f] shadow-lg"><Plus size={17} strokeWidth={2.5}/></span><div className="aspect-[16/7.5] w-full overflow-hidden bg-white/[0.018]"><ProductImage product={product} className="cashier-product-image size-full object-contain p-2"/></div><div className="p-4"><div className="text-[11px] font-bold uppercase tracking-[.08em] text-[#d7fb69]/70">{product.cashierCategory}</div><h3 className="mt-1 line-clamp-2 text-sm font-bold leading-5">{product.name}</h3>{product.needsConfiguration?<span className="mt-2 inline-flex rounded-full border border-amber-400/20 bg-amber-400/10 px-2 py-1 text-[10px] font-bold text-amber-300">Needs configuration</span>:<p className="mt-2 text-[15px] font-black text-[#d7fb69]">{CURRENCY.format(product.price)}</p>}</div></button>)}</div>}
      <div className="mt-6 grid gap-3 md:grid-cols-3">{([{id:"orders",icon:Receipt,label:"Recent Orders",value:`${shift.completedOrders} this shift`},{id:"receipts",icon:Printer,label:"Receipts",value:"View or reprint"},{id:"shift",icon:WalletCards,label:"Shift Sales",value:CURRENCY.format(shift.totalSales)}] as const).map(card=><button key={card.id} onClick={()=>setTool(card.id)} className="rounded-2xl border border-white/8 bg-white/[0.03] p-4 text-left transition hover:bg-white/[0.06] focus:outline-none focus:ring-2 focus:ring-[#d7fb69]/40"><card.icon size={18} className="text-white/35"/><strong className="mt-3 block text-sm">{card.label}</strong><small className="text-white/30">{card.value}</small></button>)}</div>
    </section>
    <aside className="cashier-order-panel flex min-h-[560px] flex-col border-t border-white/[.06] px-5 pb-24 pt-5 lg:sticky lg:top-0 lg:h-screen lg:border-l lg:border-t-0"><div className="mb-5 flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-black tracking-[-.025em]"><ShoppingCart size={18} className="text-[#d7fb69]"/>Current Order</h2><button disabled={!orderItems.length} onClick={()=>setClearConfirm(true)} className="rounded-lg px-2 py-1 text-xs font-bold text-red-300 transition-colors hover:bg-red-400/10 disabled:opacity-30">Clear</button></div><div className="flex-1 space-y-3 overflow-auto pr-1">{orderItems.length===0?<div className="grid h-56 place-items-center rounded-[18px] border border-dashed border-white/[.07] bg-white/[.012] text-center"><div><ShoppingCart size={28} className="mx-auto mb-3 text-white/20"/><p className="text-sm font-bold text-white/65">No items yet</p><p className="mt-1 text-xs text-white/35">Select menu items to begin an order.</p></div></div>:<AnimatePresence initial={false}>{orderItems.map(item=><motion.div key={item.id} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-4}} transition={{duration:.12,ease:"easeOut"}} className="cashier-cart-item rounded-[16px] p-3.5"><div className="flex justify-between gap-3"><div className="min-w-0"><strong className="line-clamp-2 text-sm">{item.name}</strong>{item.customizations.length>0&&<p className="mt-1 text-[11px] text-white/40">{item.customizations.join(" · ")}</p>}<p className="mt-1 text-xs text-white/40">{CURRENCY.format(item.unitPrice)} each</p></div><span className="shrink-0 text-sm font-black text-[#d7fb69]">{CURRENCY.format(item.unitPrice*item.quantity)}</span></div><div className="mt-3 flex items-center gap-2"><button aria-label={`Decrease ${item.name}`} onClick={()=>updateQuantity(item.id,item.quantity-1)} className="cashier-quantity grid size-9 place-items-center rounded-xl"><Minus size={13}/></button><span className="w-7 text-center text-sm font-black tabular-nums">{item.quantity}</span><button aria-label={`Increase ${item.name}`} onClick={()=>updateQuantity(item.id,item.quantity+1)} className="cashier-quantity grid size-9 place-items-center rounded-xl"><Plus size={13}/></button><button aria-label={`Remove ${item.name}`} onClick={()=>updateQuantity(item.id,0)} className="ml-auto rounded-xl p-2.5 text-white/35 transition-colors hover:bg-red-500/10 hover:text-red-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400/40"><Trash2 size={15}/></button></div></motion.div>)}</AnimatePresence>}</div>
      <div className="mt-4 space-y-2.5 border-t border-white/10 pt-5 text-sm"><div className="flex justify-between text-white/48"><span>Subtotal</span><span className="tabular-nums">{CURRENCY.format(subtotal)}</span></div><div className="flex justify-between text-white/48"><span>Tax (8%)</span><span className="tabular-nums">{CURRENCY.format(tax)}</span></div><div className="mt-2 flex items-end justify-between border-t border-white/[.06] pt-4"><span className="text-base font-black">Total</span><span className="text-[1.7rem] font-black tracking-[-.04em] text-[#d7fb69] tabular-nums">{CURRENCY.format(total)}</span></div><p className="pt-2 text-[10px] font-bold uppercase tracking-[.14em] text-white/30">Payment</p><button disabled={!orderItems.length||!registerOpen} onClick={()=>setCashOpen(true)} className={`${button} h-12 w-full bg-[#d7fb69] text-[#17200f]`}><Banknote size={17} className="mr-2 inline"/>Cash</button><button disabled className={`${button} h-11 w-full border border-white/10 bg-white/5 text-white/35`}><CreditCard size={16} className="mr-2 inline"/>Card · Coming Soon</button></div></aside></div>

    {customizing&&<Modal title={`Customize ${customizing.name}`} onClose={()=>{setCustomizing(null);setSelections({});}}>{customizing.customizationGroups.filter(group=>group.required).map(group=><fieldset key={group.id} className="mb-5"><legend className="mb-2 text-sm font-bold">{group.name}<span className="ml-2 text-xs text-[#d7fb69]">Required</span></legend><div className="space-y-2">{group.options.map(option=><label key={option.id} className={`flex cursor-pointer items-center justify-between rounded-xl border p-3 text-sm ${selections[group.id]===option.id?"border-[#d7fb69]/50 bg-[#d7fb69]/10":"border-white/10 bg-white/[0.03]"}`}><span><input type="radio" name={group.id} checked={selections[group.id]===option.id} onChange={()=>setSelections(current=>({...current,[group.id]:option.id}))} className="mr-3 accent-[#d7fb69]"/>{option.name}</span>{option.priceAdjustment!==0&&<span className="text-white/45">+{CURRENCY.format(option.priceAdjustment)}</span>}</label>)}</div></fieldset>)}<div className="flex justify-end gap-2"><button onClick={()=>setCustomizing(null)} className={`${button} bg-white/5`}>Cancel</button><button onClick={confirmCustomization} className={`${button} bg-[#d7fb69] text-[#17200f]`}>Add to Order</button></div></Modal>}
    {clearConfirm&&<Modal title="Clear current order?" onClose={()=>setClearConfirm(false)}><p className="text-sm text-white/55">All items will be removed from this order.</p><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setClearConfirm(false)} className={`${button} bg-white/5`}>Cancel</button><button onClick={()=>{setOrderItems([]);setClearConfirm(false);}} className={`${button} bg-red-500 text-white`}>Clear Order</button></div></Modal>}
    {cashOpen&&<Modal title="Cash Payment" onClose={()=>{setCashOpen(false);setReceived("");}}><div className="space-y-4"><div className="rounded-xl bg-[#d7fb69]/10 p-4"><p className="text-xs text-white/40">Total Due</p><p className="mt-1 text-3xl font-black text-[#d7fb69]">{CURRENCY.format(total)}</p></div><label className="block text-xs text-white/50">Amount Received<input autoFocus type="number" min="0" step="0.01" value={received} onChange={event=>setReceived(event.target.value)} className="mt-1 h-12 w-full rounded-xl border border-white/10 bg-white/5 px-4 text-lg outline-none focus:border-[#d7fb69]/50"/></label><div className="flex justify-between rounded-xl border border-white/8 p-4"><span className="text-white/45">Change</span><strong className="text-[#d7fb69]">{CURRENCY.format(change)}</strong></div>{received&&amountReceived<total&&<p className="text-xs text-red-300">Amount received must cover the total due.</p>}<p className="text-[11px] text-white/30">Demo mode: no real payment is processed.</p><button disabled={!received||amountReceived<total} onClick={completeSale} className={`${button} h-12 w-full bg-[#d7fb69] text-[#17200f]`}>Complete Sale</button></div></Modal>}
    {completedReceipt&&<Modal title="Sale Completed" onClose={()=>setCompletedReceipt(null)} wide><div className="flex max-h-[62vh] justify-center overflow-y-auto rounded-xl bg-[#0b0f0b] p-4 sm:p-5"><CashierReceipt receipt={completedReceipt} mode="preview"/></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setCompletedReceipt(null)} className={`${button} bg-white/5`}>Close</button><button onClick={()=>printReceipt(completedReceipt)} className={`${button} bg-[#d7fb69] text-[#17200f]`}><Printer size={14} className="mr-2 inline"/>Print Receipt</button></div></Modal>}
    {tool&&<Modal title={tool==="orders"?"Recent Orders":tool==="receipts"?"Receipt History":"Shift Sales"} onClose={()=>setTool(null)} wide={tool!=="shift"}>{tool==="shift"?<div className="grid grid-cols-2 gap-3">{[["Total Sales",CURRENCY.format(shift.totalSales)],["Completed Orders",shift.completedOrders],["Cash Total",CURRENCY.format(shift.cashTotal)],["Card Total",CURRENCY.format(shift.cardTotal)]].map(([label,value])=><div key={label} className="rounded-xl border border-white/8 bg-white/[0.03] p-4"><small className="text-white/35">{label}</small><strong className="mt-1 block text-xl">{value}</strong></div>)}</div>:recentOrders.length===0?<p className="py-8 text-center text-sm text-white/35">No completed cashier orders yet.</p>:<div className="space-y-2">{recentOrders.map(order=><div key={order.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-white/8 bg-white/[0.03] p-3 text-sm"><div className="min-w-32"><strong>{order.id}</strong><div className="mt-1 flex items-center gap-2 text-xs text-white/40"><span>{order.time} · {order.paymentMethod}</span><span className="cashier-status cashier-status-completed">{order.status}</span></div></div><span className="ml-auto font-bold text-[#d7fb69]">{CURRENCY.format(order.total)}</span>{tool==="orders"&&<button onClick={()=>setSelectedOrder(order)} className="rounded-lg bg-white/8 px-3 py-2 text-xs">View Order</button>}<button onClick={()=>printReceipt(order.receipt)} className="rounded-lg bg-white/8 px-3 py-2 text-xs"><Printer size={13} className="mr-1 inline"/>Reprint</button></div>)}</div>}</Modal>}
    {selectedOrder&&<Modal title={selectedOrder.id} onClose={()=>setSelectedOrder(null)} wide><div className="flex max-h-[62vh] justify-center overflow-y-auto rounded-xl bg-[#0b0f0b] p-4 sm:p-5"><CashierReceipt receipt={selectedOrder.receipt} mode="preview"/></div><button onClick={()=>printReceipt(selectedOrder.receipt)} className={`${button} mt-5 bg-[#d7fb69] text-[#17200f]`}><Printer size={14} className="mr-2 inline"/>Reprint Receipt</button></Modal>}
    {closeConfirm&&<Modal title="Close register?" onClose={()=>setCloseConfirm(false)}><p className="text-sm text-white/55">This will end the current cashier shift.</p><div className="my-5 grid grid-cols-2 gap-3">{[["Total Orders",shift.completedOrders],["Total Sales",CURRENCY.format(shift.totalSales)],["Cash Sales",CURRENCY.format(shift.cashTotal)],["Card Sales",CURRENCY.format(shift.cardTotal)]].map(([label,value])=><div key={label} className="rounded-xl bg-white/5 p-3"><small className="text-white/35">{label}</small><strong className="mt-1 block">{value}</strong></div>)}</div><div className="flex justify-end gap-2"><button onClick={()=>setCloseConfirm(false)} className={`${button} bg-white/5`}>Cancel</button><button onClick={()=>{setRegisterOpen(false);setCloseConfirm(false);toast.success("Register closed for this demo shift.");}} className={`${button} bg-red-500 text-white`}>Close Register</button></div></Modal>}
  </main>;
}
