import { useMemo, useState } from "react";
import { Banknote, Minus, Plus, Printer, Receipt, Search, ShoppingCart, Store, WalletCards, X } from "lucide-react";
import { useCart } from "../context/CartContext";

const REGISTER_ITEMS = [
  { id:"b1", name:"Spicy Nori Burger", price:8.9, category:"Burger", image:"https://images.unsplash.com/photo-1606149059549-6042addafc5a?fit=crop&w=300&q=80" },
  { id:"b2", name:"Smoky Truffle Beef", price:10.5, category:"Burger", image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?fit=crop&w=300&q=80" },
  { id:"s1", name:"Rosemary Fries", price:3.5, category:"Side", image:"https://images.unsplash.com/photo-1573080496219-bb080dd4f877?fit=crop&w=300&q=80" },
  { id:"d1", name:"Iced Matcha Latte", price:4.5, category:"Drink", image:"https://images.unsplash.com/photo-1543007630-9710e4a00a20?fit=crop&w=300&q=80" },
] as const;
type Tool = "orders" | "receipts" | "shift";

export default function CashierDashboard() {
  const { items, user, addItem, updateQty, subtotal, tax, total, clearCart, setPaymentMethod, placeOrder } = useCart();
  const [search,setSearch]=useState(""); const [registerOpen,setRegisterOpen]=useState(true); const [notice,setNotice]=useState(""); const [tool,setTool]=useState<Tool|null>(null);
  const todayOrders = useMemo(() => user.orderHistory.filter(order => order.date === new Date().toISOString().slice(0,10)), [user.orderHistory]);
  const shiftSales = todayOrders.reduce((sum,order)=>sum+order.total,0);
  const pay=()=>{ if(!items.length)return; setPaymentMethod("cash"); placeOrder(); setNotice("Payment accepted · Receipt ready to print"); clearCart(); };
  const printReceipt=()=>window.print();
  return <main className="min-h-screen bg-[#07090a] text-white font-['DM_Sans'] flex flex-col">
    <header className="border-b border-white/5 px-6 py-4 flex items-center justify-between"><div className="flex items-center gap-3"><div className="size-10 rounded-xl bg-violet-500/15 border border-violet-500/25 text-violet-400 grid place-items-center"><Store size={18}/></div><div><h1 className="font-bold">Morrow Register</h1><p className="text-xs text-white/35">Downtown · Current shift</p></div></div><button onClick={()=>setRegisterOpen(value=>!value)} className={`px-4 py-2 rounded-xl text-xs font-bold border ${registerOpen?"bg-emerald-500/10 border-emerald-500/20 text-emerald-400":"bg-red-500/10 border-red-500/20 text-red-400"}`}>{registerOpen?"Close register":"Open register"}</button></header>
    <div className="flex-1 grid lg:grid-cols-[1fr_390px] min-h-0"><section className="p-6"><div className="relative mb-5"><Search size={17} className="absolute left-4 top-3.5 text-white/30"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search menu…" className="h-12 w-full rounded-2xl border border-white/10 bg-white/[0.04] pl-11 pr-4 outline-none focus:border-violet-400/40"/></div>
      <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{REGISTER_ITEMS.filter(item=>item.name.toLowerCase().includes(search.toLowerCase())).map(item=><button key={item.id} disabled={!registerOpen} onClick={()=>addItem({...item,basePrice:item.price})} className="overflow-hidden rounded-2xl border border-white/8 bg-white/[0.03] text-left hover:bg-white/[0.06] disabled:opacity-40"><img src={item.image} alt="" className="h-32 w-full object-cover"/><div className="p-4"><small className="text-violet-400">{item.category}</small><h3 className="font-bold mt-1">{item.name}</h3><p className="text-[#d7ff7a] font-black mt-2">${item.price.toFixed(2)}</p></div></button>)}</div>
      <div className="grid md:grid-cols-3 gap-3 mt-6">{([{id:"orders",icon:Receipt,label:"Recent orders",value:`${todayOrders.length} today`},{id:"receipts",icon:Printer,label:"Receipts",value:"Print or reprint"},{id:"shift",icon:WalletCards,label:"Shift sales",value:`$${shiftSales.toFixed(2)}`} ] as const).map(card=><button key={card.id} onClick={()=>setTool(card.id)} className="rounded-2xl bg-white/[0.03] border border-white/8 p-4 text-left hover:bg-white/[0.06]"><card.icon size={18} className="text-white/35"/><strong className="block text-sm mt-3">{card.label}</strong><small className="text-white/30">{card.value}</small></button>)}</div>
      {tool && <div className="mt-4 rounded-2xl border border-violet-500/20 bg-violet-500/5 p-5"><div className="flex justify-between"><h3 className="font-bold capitalize">{tool}</h3><button onClick={()=>setTool(null)}><X size={16}/></button></div>{tool==="orders"&&<div className="mt-3 space-y-2">{user.orderHistory.slice(0,6).map(order=><div key={order.id} className="flex justify-between rounded-xl bg-black/20 p-3 text-sm"><span>{order.id} · {order.items.length} items</span><span>${order.total.toFixed(2)}</span></div>)}</div>}{tool==="receipts"&&<button onClick={printReceipt} className="mt-4 rounded-xl bg-[#d7ff7a] px-5 py-2 text-sm font-bold text-[#17200f]"><Printer size={14} className="inline mr-2"/>Print last receipt</button>}{tool==="shift"&&<div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-black/20 p-4"><small className="text-white/35">Orders</small><strong className="block text-xl">{todayOrders.length}</strong></div><div className="rounded-xl bg-black/20 p-4"><small className="text-white/35">Net sales</small><strong className="block text-xl text-[#d7ff7a]">${shiftSales.toFixed(2)}</strong></div></div>}</div>}
    </section><aside className="border-l border-white/5 bg-[#0a0d0a] px-5 pt-5 pb-24 flex flex-col"><div className="flex items-center justify-between mb-5"><h2 className="font-black flex items-center gap-2"><ShoppingCart size={17}/> Current order</h2><button onClick={clearCart} className="text-xs text-red-400">Clear</button></div><div className="flex-1 space-y-3 overflow-auto">{items.length===0?<div className="h-48 grid place-items-center text-center text-white/25 text-sm">Select menu items to start<br/>a customer order.</div>:items.map(item=><div key={item.id} className="rounded-xl border border-white/8 bg-white/[0.03] p-3"><div className="flex justify-between gap-3"><strong className="text-sm">{item.name}</strong><span className="text-sm text-[#d7ff7a]">${(item.price*item.qty).toFixed(2)}</span></div><div className="flex items-center gap-3 mt-3"><button onClick={()=>updateQty(item.id,item.qty-1)} className="size-7 rounded-lg bg-white/8 grid place-items-center"><Minus size={12}/></button><span className="text-sm font-bold">{item.qty}</span><button onClick={()=>updateQty(item.id,item.qty+1)} className="size-7 rounded-lg bg-white/8 grid place-items-center"><Plus size={12}/></button></div></div>)}</div><div className="border-t border-white/10 pt-4 space-y-2 text-sm"><div className="flex justify-between text-white/45"><span>Subtotal</span><span>${subtotal.toFixed(2)}</span></div><div className="flex justify-between text-white/45"><span>Tax</span><span>${tax.toFixed(2)}</span></div><div className="flex justify-between text-lg font-black"><span>Total</span><span className="text-[#d7ff7a]">${total.toFixed(2)}</span></div>{notice&&<p className="rounded-xl bg-emerald-500/10 text-emerald-400 p-3 text-xs">{notice}</p>}<button disabled={!items.length||!registerOpen} onClick={pay} className="w-full h-13 rounded-xl bg-[#d7ff7a] text-[#17200f] font-black disabled:opacity-30"><Banknote size={17} className="inline mr-2"/>Accept cash payment</button></div></aside></div>
  </main>;
}
