import { useState, type FormEvent } from "react";
import { ArrowLeft, Check, LockKeyhole, MonitorCog, Trash2 } from "lucide-react";
import { DEVICE_MANAGER_PIN } from "../auth/mockCredentials";
import { useAuth } from "../auth/AuthContext";
import type { DeviceMode } from "../auth/roleConfig";

const MODES: DeviceMode[] = ["customer", "admin", "cashier", "kitchen", "display"];
export default function DeviceSetup({ onClose, onSelectRole }: { onClose: () => void; onSelectRole: () => void }) {
  const { selectedDeviceMode, selectDeviceMode, clearDeviceMode, logout } = useAuth();
  const [unlocked, setUnlocked] = useState(false); const [pin, setPin] = useState(""); const [error, setError] = useState(false);
  const verify = (e: FormEvent) => { e.preventDefault(); if (pin === DEVICE_MANAGER_PIN) { setUnlocked(true); setError(false); } else setError(true); };
  if (!unlocked) return <main className="min-h-screen bg-[#07090a] text-white grid place-items-center p-6"><form onSubmit={verify} className="w-full max-w-sm rounded-3xl border border-white/10 bg-white/[0.04] p-8"><div className="size-12 rounded-2xl bg-[#d7ff7a]/10 text-[#d7ff7a] grid place-items-center mb-5"><LockKeyhole/></div><h1 className="text-2xl font-black">Device settings</h1><p className="text-sm text-white/40 mt-2">Manager authorization is required.</p><input autoFocus value={pin} onChange={e=>setPin(e.target.value)} inputMode="numeric" type="password" maxLength={8} placeholder="Manager PIN" className="mt-6 h-12 w-full rounded-xl border border-white/10 bg-white/5 px-4 outline-none focus:border-[#d7ff7a]/40"/>{error&&<p className="text-red-400 text-sm mt-3">Incorrect manager PIN.</p>}<button className="mt-4 h-12 w-full rounded-xl bg-[#d7ff7a] text-[#17200f] font-black">Unlock settings</button><button type="button" onClick={onClose} className="mt-3 w-full py-2 text-sm text-white/35 hover:text-white"><ArrowLeft size={14} className="inline mr-2"/>Return</button></form></main>;
  return <main className="min-h-screen bg-[#07090a] text-white p-6 md:p-10"><div className="max-w-4xl mx-auto"><header className="flex items-center gap-4 mb-10"><div className="size-12 rounded-2xl bg-[#d7ff7a] text-[#17200f] grid place-items-center"><MonitorCog/></div><div><h1 className="text-2xl font-black">Device mode</h1><p className="text-sm text-white/35">Current assignment: <strong className="text-[#d7ff7a] capitalize">{selectedDeviceMode}</strong></p></div></header><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{MODES.map(mode=><button key={mode} onClick={()=>{logout();selectDeviceMode(mode,true);}} className={`rounded-2xl border p-5 text-left capitalize ${selectedDeviceMode===mode?"border-[#d7ff7a]/40 bg-[#d7ff7a]/10":"border-white/10 bg-white/[0.03] hover:bg-white/[0.06]"}`}><div className="flex justify-between"><strong>{mode}</strong>{selectedDeviceMode===mode&&<Check size={16} className="text-[#d7ff7a]"/>}</div><p className="text-xs text-white/35 mt-2">Assign this device permanently to the {mode} workspace.</p></button>)}</div><div className="mt-8 flex flex-wrap gap-3"><button onClick={onClose} className="px-5 py-3 rounded-xl bg-[#d7ff7a] text-[#17200f] font-bold">Apply and open workspace</button><button onClick={()=>{logout(true);clearDeviceMode();onSelectRole();}} className="px-5 py-3 rounded-xl border border-red-500/20 bg-red-500/10 text-red-400 font-bold"><Trash2 size={15} className="inline mr-2"/>Clear mode and return to selection</button></div></div></main>;
}
