import { useState } from "react";
import { Accessibility, ArrowRight, ChevronLeft, Globe2, Heart, Mic, QrCode, Search, Sparkles, UtensilsCrossed, Volume2 } from "lucide-react";
import MorrowLogo from "../components/branding/MorrowLogo";

const hero = "https://images.unsplash.com/photo-1606149059549-6042addafc5a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1200";
const screens = ["Splash","Welcome","Language","Access","Service","Guest login","Loyalty","Home","Categories","Search","Voice search","AI ordering","Listing","Favorites","Offers","Recommendations","Recent","Popular"];
const food = ["Crispy Nori","Smoky Truffle","Golden fries"];
const Card=({name,small=false}:{name:string;small?:boolean})=><article className={`overflow-hidden rounded-[22px] border border-white/10 bg-white/[.055] ${small?"":"min-w-[220px]"}`}><img src={hero} alt="Gourmet burger" className={`${small?"h-24":"h-32"} w-full object-cover opacity-85`}/><div className="p-3"><div className="flex justify-between gap-2"><b className="text-sm">{name}</b><b className="font-['Space_Mono'] text-xs text-[#d7ff7a]">$8.90</b></div><p className="mt-1 text-[11px] text-white/45">Crispy chicken · pickles</p></div></article>;
const Action=({children,onClick,soft=false}:{children:React.ReactNode;onClick?:()=>void;soft?:boolean})=><button onClick={onClick} className={`rounded-2xl px-5 py-4 text-sm font-semibold transition active:scale-[.98] ${soft?"border border-white/15 bg-white/5":"bg-[#d7ff7a] text-[#17200f]"}`}>{children}</button>;

export default function KioskJourneyOriginal({ onBackToSelection }: { onBackToSelection?: () => void }) {
  const [screen,setScreen]=useState("Splash");const [lang,setLang]=useState("English");const [access,setAccess]=useState(false);const [query,setQuery]=useState("");const [favorite,setFavorite]=useState(false);const [voice,setVoice]=useState(false);const [ai,setAi]=useState("");
const basic=<div className="flex min-h-full flex-col p-7 md:p-10"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><MorrowLogo variant="full" className="h-auto w-32" /><small className="font-['Space_Mono'] text-[9px] tracking-widest text-[#d7ff7a]">KIOSK 04</small></div><div className="flex items-center gap-2"><button onClick={()=>setScreen("Access")} className="grid size-11 place-items-center rounded-xl border border-white/15"><Accessibility size={20}/></button>{onBackToSelection && <button onClick={onBackToSelection} className="rounded-xl border border-white/15 px-4 py-2.5 text-xs hover:bg-white/10 font-semibold text-white">Exit Demo</button>}</div></div></div>;
const center=(eyebrow:string,title:string,copy:string,actions:React.ReactNode)=><div className="flex min-h-full flex-col justify-center px-8 py-12 text-center md:px-16"><p className="font-['Space_Mono'] text-[10px] tracking-[.24em] text-[#d7ff7a]">{eyebrow}</p><h1 className="mt-5 text-5xl font-semibold leading-[.96] tracking-[-.06em] md:text-7xl">{title}</h1><p className="mx-auto mt-6 max-w-lg text-base leading-7 text-white/60">{copy}</p><div className="mt-9 flex flex-wrap justify-center gap-3">{actions}</div></div>;
let content:React.ReactNode;
switch(screen){
case "Splash": content=<div className="relative grid min-h-full place-items-center overflow-hidden bg-[#11150e]"><div className="absolute size-[600px] rounded-full bg-[#d7ff7a]/10 blur-3xl"/><div className="relative text-center"><MorrowLogo variant="full" priority className="mx-auto h-auto w-64" /><p className="mt-5 font-['Space_Mono'] text-[10px] tracking-[.3em] text-[#d7ff7a]">GOOD FOOD, QUIETLY FAST</p></div><button onClick={()=>setScreen("Welcome")} className="absolute bottom-10 right-10 flex items-center gap-2 text-sm text-white/55">Tap to begin <ArrowRight size={18}/></button></div>;break;
case "Welcome": content=<div className="relative min-h-full overflow-hidden"><img src={hero} alt="Burger meal" className="absolute inset-0 size-full object-cover opacity-45"/><div className="absolute inset-0 bg-gradient-to-r from-[#11150e] via-[#11150e]/85 to-[#11150e]/25"/>{basic}<div className="relative -mt-14">{center("WELCOME TO MORROW","Make it a good one.","Thoughtfully made food, exactly the way you like it.",<><Action onClick={()=>setScreen("Language")}>Start order <ArrowRight className="ml-2 inline size-4"/></Action><Action soft onClick={()=>setScreen("Access")}>Accessibility options</Action></>)}</div></div>;break;
case "Language":content=<>{basic}{center("CHOOSE YOUR LANGUAGE","Let’s speak your language.","You can change this any time during your order.",<>{["English","العربية","Türkçe"].map(x=><Action key={x} soft={lang!==x} onClick={()=>{setLang(x);setScreen("Service")}}>{x}</Action>)}</>)}</>;break;
case "Access":content=<>{basic}<div className="px-8 pb-10 md:px-16"><p className="font-['Space_Mono'] text-[10px] tracking-widest text-[#d7ff7a]">ACCESSIBILITY</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.05em]">Set up your experience.</h1><div className="mt-8 grid gap-4 md:grid-cols-2">{[["Larger text","Increase sizing across this kiosk"],["High contrast","Make controls and type more distinct"],["Screen reader","Hear every option aloud"],["Reduce motion","Minimize transitions and movement"]].map(([a,b])=><button key={a} onClick={()=>setAccess(!access)} className={`flex min-h-28 items-center justify-between rounded-2xl border p-5 text-left ${access?"border-[#d7ff7a] bg-[#d7ff7a]/10":"border-white/10 bg-white/[.035]"}`}><span><b>{a}</b><small className="mt-1 block text-xs text-white/50">{b}</small></span><span className={`size-7 rounded-full border ${access?"border-[#d7ff7a] bg-[#d7ff7a]":"border-white/25"}`}/></button>)}</div><div className="mt-8"><Action onClick={()=>setScreen("Service")}>Continue</Action></div></div></>;break;
case "Service":content=<>{basic}{center("HOW ARE YOU DINING?","Made for your moment.","Tell us where you’ll enjoy your meal so we can prepare it perfectly.",<><Action onClick={()=>setScreen("Guest login")}>Eat here</Action><Action soft onClick={()=>setScreen("Guest login")}>Take away</Action></>)}</>;break;
case "Guest login":content=<>{basic}{center("YOUR ORDER, YOUR WAY","Order as a guest?","Save your favorite orders and collect points whenever you’re ready.",<><Action onClick={()=>setScreen("Home")}>Continue as guest</Action><Action soft onClick={()=>setScreen("Loyalty")}><QrCode className="mr-2 inline size-4"/> Sign in for rewards</Action></>)}</>;break;
case "Loyalty":content=<>{basic}{center("MORROW REWARDS","Welcome back.","Scan your loyalty code or enter the mobile number linked to your account.",<div className="w-full max-w-md"><div className="flex rounded-2xl border border-white/15 bg-white/5 p-2"><input placeholder="Mobile number" className="min-w-0 flex-1 bg-transparent px-3 outline-none placeholder:text-white/35"/><Action onClick={()=>setScreen("Home")}>Continue</Action></div><button className="mt-5 text-sm text-[#d7ff7a]"><QrCode className="mr-2 inline size-4"/> Scan QR code</button></div>)}</>;break;
case "Home":content=<>{basic}<div className="px-7 pb-8 md:px-10"><div className="mt-4 flex items-end justify-between"><div><p className="font-['Space_Mono'] text-[10px] tracking-widest text-[#d7ff7a]">GOOD AFTERNOON</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.05em]">What sounds good?</h1></div><button onClick={()=>setScreen("Search")} className="rounded-xl border border-white/15 p-3"><Search/></button></div><div onClick={()=>setScreen("Offers")} className="mt-6 cursor-pointer overflow-hidden rounded-[26px] bg-[#a9cc50] p-6 text-[#16200b]"><p className="font-['Space_Mono'] text-[10px] tracking-widest">TODAY’S DROP</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.05em]">The crisp is<br/>calling.</h2><p className="mt-2 text-sm opacity-70">A chicken classic plus fries · $13.50</p></div><div className="mt-7 flex gap-3 overflow-auto pb-2">{["Burgers","Chicken","Sides","Drinks","Desserts"].map(x=><button key={x} onClick={()=>setScreen("Categories")} className="shrink-0 rounded-full border border-white/15 px-5 py-3 text-sm">{x}</button>)}</div><h2 className="mt-7 text-xl font-semibold">Made for you</h2><div className="mt-4 flex gap-4 overflow-auto pb-2">{food.map(x=><Card key={x} name={x}/>)}</div></div></>;break;
case "Categories":content=<>{basic}<div className="px-7 pb-8 md:px-10"><button onClick={()=>setScreen("Home")} className="mt-5 flex items-center gap-1 text-sm text-white/55"><ChevronLeft size={18}/> Back</button><h1 className="mt-6 text-4xl font-semibold tracking-[-.05em]">{lang === "العربية" ? "استكشف القائمة" : "Explore the menu"}</h1><div className="mt-7 grid grid-cols-2 gap-4 md:grid-cols-3">{["Burgers","Chicken","Combos","Sides","Drinks","Desserts"].map((x,i)=><button key={x} onClick={()=>setScreen("Listing")} className="min-h-36 rounded-[24px] border border-white/10 bg-white/[.04] p-5 text-left hover:bg-white/[.08]"><span className="font-['Space_Mono'] text-[10px] text-[#d7ff7a]">0{i+1}</span><b className="mt-10 block text-xl">{x}</b></button>)}</div></div></>;break;
case "Search":content=<>{basic}<div className="px-7 md:px-10"><button onClick={()=>setScreen("Home")} className="mt-5 text-sm text-white/55">← Back to menu</button><h1 className="mt-6 text-3xl font-semibold">Find exactly what you want.</h1><div className="mt-6 flex h-16 items-center gap-3 rounded-2xl border border-[#d7ff7a]/50 bg-white/5 px-5"><Search className="text-[#d7ff7a]"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the menu" className="min-w-0 flex-1 bg-transparent text-lg outline-none placeholder:text-white/35"/><button onClick={()=>setScreen("Voice search")}><Mic className="text-[#d7ff7a]"/></button></div><div className="mt-8"><p className="text-sm text-white/45">Popular searches</p><div className="mt-3 flex flex-wrap gap-2">{["Spicy","High protein","Vegetarian","Under $10"].map(x=><button key={x} onClick={()=>{setQuery(x);setScreen("Listing")}} className="rounded-full bg-white/10 px-4 py-2 text-sm">{x}</button>)}</div></div></div></>;break;
case "Voice search":content=<>{basic}{center("VOICE ORDERING",voice?"I’m listening.":"Speak your craving.",voice?"Try ‘I’d like two spicy chicken burgers with fries.’":"Tap the microphone and tell us what you’re in the mood for.",<Action onClick={()=>setVoice(!voice)}><Mic className="mr-2 inline"/> {voice?"Listening…":"Start speaking"}</Action>)}</>;break;
case "AI ordering":content=<>{basic}{center("MEET NORI","Your food guide.","Tell Nori your budget, mood, dietary needs, or simply what you feel like eating.",<div className="w-full max-w-xl"><div className="flex rounded-2xl border border-[#d7ff7a]/35 bg-white/[.06] p-2"><Sparkles className="m-3 text-[#d7ff7a]"/><input value={ai} onChange={e=>setAi(e.target.value)} placeholder="Try ‘something fresh and high protein’" className="min-w-0 flex-1 bg-transparent outline-none placeholder:text-white/35"/><Action onClick={()=>setScreen("Recommendations")}>Ask</Action></div><div className="mt-4 flex flex-wrap justify-center gap-2">{["Under $10","Vegetarian","Peanut-free"].map(x=><button key={x} onClick={()=>setAi(x)} className="rounded-full bg-white/10 px-3 py-2 text-xs">{x}</button>)}</div></div>)}</>;break;
case "Listing":content=<>{basic}<div className="px-7 pb-8 md:px-10"><button onClick={()=>setScreen("Categories")} className="mt-5 text-sm text-white/55">← Categories</button><div className="mt-5 flex items-end justify-between"><h1 className="text-4xl font-semibold">Burgers</h1><span className="text-sm text-white/45">12 items</span></div><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[...food,...food].map((x,i)=><div key={i} onClick={()=>setFavorite(!favorite)} className="cursor-pointer"><Card name={x}/><button className="relative -mt-12 ml-4 rounded-lg bg-black/50 p-2"><Heart className={favorite?"fill-[#ff8e82] text-[#ff8e82]":""} size={16}/></button></div>)}</div></div></>;break;
case "Favorites":content=<>{basic}<div className="px-7 md:px-10"><h1 className="mt-8 text-4xl font-semibold">Your favorites</h1><p className="mt-2 text-white/55">The orders worth repeating.</p><div className="mt-7 flex gap-4 overflow-auto">{food.map(x=><Card key={x} name={x}/>)}</div></div></>;break;
case "Offers":content=<>{basic}<div className="px-7 md:px-10"><p className="mt-7 font-['Space_Mono'] text-[10px] tracking-widest text-[#d7ff7a]">LIMITED TODAY</p><h1 className="mt-3 text-4xl font-semibold">Worth a detour.</h1><div className="mt-7 grid gap-4 md:grid-cols-2"><div className="rounded-[26px] bg-[#ffb86c] p-7 text-[#382306]"><p className="font-['Space_Mono'] text-[10px] tracking-widest">MEAL FOR TWO</p><h2 className="mt-5 text-3xl font-semibold">Two crisps, two fries, all good.</h2><Action soft>Choose this offer</Action></div><div className="rounded-[26px] bg-[#d7ff7a] p-7 text-[#17200f]"><p className="font-['Space_Mono'] text-[10px] tracking-widest">REWARDS</p><h2 className="mt-5 text-3xl font-semibold">Double points after 2pm.</h2></div></div></div></>;break;
case "Recommendations":content=<>{basic}<div className="px-7 md:px-10"><p className="mt-7 flex items-center gap-2 font-['Space_Mono'] text-[10px] tracking-widest text-[#d7ff7a]"><Sparkles size={14}/> NORI RECOMMENDS</p><h1 className="mt-3 text-4xl font-semibold">A little more you.</h1><p className="mt-3 text-white/55">High protein, rich flavor, and under 10 minutes.</p><div className="mt-7 flex gap-4 overflow-auto">{food.map(x=><Card key={x} name={x}/>)}</div></div></>;break;
case "Recent":content=<>{basic}<div className="px-7 md:px-10"><h1 className="mt-8 text-4xl font-semibold">Order it again?</h1><p className="mt-3 text-white/55">Your last few favorites, ready when you are.</p><div className="mt-7 flex gap-4 overflow-auto">{food.map(x=><Card key={x} name={x}/>)}</div></div></>;break;
default:content=<>{basic}<div className="px-7 md:px-10"><h1 className="mt-8 text-4xl font-semibold">Everyone’s ordering these.</h1><div className="mt-7 grid gap-4 md:grid-cols-3">{food.map(x=><Card key={x} name={x}/>)}</div></div></>}
return <main className="min-h-screen bg-[#0f120e] font-['DM_Sans'] text-[#f8f8f3]"><div className="mx-auto grid min-h-screen max-w-[1900px] lg:grid-cols-[230px_1fr]"><aside className="hidden border-r border-white/10 bg-[#10130f] p-5 lg:block"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-[#d7ff7a] text-black"><UtensilsCrossed size={16}/></span><b>Flow library (Orig)</b></div><p className="mt-7 font-['Space_Mono'] text-[9px] tracking-[.2em] text-white/35">CUSTOMER JOURNEY</p><nav className="mt-3 max-h-[calc(100vh-135px)] space-y-1 overflow-auto">{screens.map((x,i)=><button key={x} onClick={()=>setScreen(x)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm ${screen===x?"bg-[#d7ff7a] font-semibold text-[#17200f]":"text-white/55 hover:bg-white/5"}`}><span className="font-['Space_Mono'] text-[9px] opacity-50">{String(i+1).padStart(2,"0")}</span>{x}</button>)}</nav></aside><section className="relative min-h-screen overflow-hidden"><div className="absolute right-5 top-5 z-20 flex gap-2 lg:hidden"><button onClick={()=>setScreen("Home")} className="rounded-lg bg-white/10 px-3 py-2 text-xs">Home</button></div>{content}<div className="absolute bottom-5 left-7 hidden items-center gap-2 text-[10px] text-white/30 md:flex"><Globe2 size={12}/>{lang}<span>·</span><Volume2 size={12}/>Sound on</div></section></div></main>}
