import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { AlertTriangle, ArrowRight, Bell, Check, ChefHat, Clock, Flame, Package, RefreshCw, Search, Users, X, Zap } from "lucide-react";
import { toast, Toaster } from "sonner";
import { useCart, type KitchenOrder, type OrderStatus, type PreparationStation } from "../context/CartContext";
import MorrowLogo from "../components/branding/MorrowLogo";
import { useKitchenOrders } from "../hooks/useRealtimeOrders";
import { getKitchenAction } from "../services/supabase/orderStatusService";
import { COMPLETED_KITCHEN_VISIBILITY_MS } from "../services/supabase/kitchenOrderService";

type Props = { onNavigate: (route: string) => void };
type Column = { id: OrderStatus; label: string; color: string; icon: ReactNode; empty: string };
type Severity = "normal" | "approaching" | "delayed" | "severe";
const STAGES:OrderStatus[]=["received","preparing","cooking","ready","completed"];
const COLUMNS:Column[]=[
  {id:"received",label:"Incoming",color:"blue",icon:<Package size={16}/>,empty:"No incoming orders."},
  {id:"preparing",label:"Preparing",color:"violet",icon:<Clock size={16}/>,empty:"No orders being prepared."},
  {id:"cooking",label:"Cooking",color:"orange",icon:<Flame size={16}/>,empty:"No orders cooking."},
  {id:"ready",label:"Ready",color:"lime",icon:<ChefHat size={16}/>,empty:"No orders ready."},
  {id:"completed",label:"Completed",color:"green",icon:<Check size={16}/>,empty:"No recently completed orders."},
];
const colorBg:Record<string,string>={blue:"bg-blue-500/10 border-blue-500/20 text-blue-400",violet:"bg-violet-500/10 border-violet-500/20 text-violet-400",orange:"bg-orange-500/10 border-orange-500/20 text-orange-400",lime:"bg-[#d7ff7a]/10 border-[#d7ff7a]/20 text-[#d7ff7a]",green:"bg-emerald-500/10 border-emerald-500/20 text-emerald-400"};
const colBorder:Record<string,string>={blue:"border-t-blue-500",violet:"border-t-violet-500",orange:"border-t-orange-500",lime:"border-t-[#d7ff7a]",green:"border-t-emerald-500"};

export function formatElapsedDuration(totalMinutes:number){const minutes=Math.max(0,Math.floor(totalMinutes));if(minutes<60)return `${minutes}m`;const hours=Math.floor(minutes/60);const remainder=minutes%60;if(hours<24)return `${hours}h${remainder?` ${remainder}m`:""}`;const days=Math.floor(hours/24);const remainingHours=hours%24;return `${days}d${remainingHours?` ${remainingHours}h`:""}`;}
function formatAverage(seconds:number){if(seconds<60)return `${Math.round(seconds)}s`;const minutes=Math.floor(seconds/60),remaining=Math.round(seconds%60);if(minutes<60)return `${minutes}m${remaining?` ${remaining}s`:""}`;const hours=Math.floor(minutes/60),rest=minutes%60;return `${hours}h${rest?` ${rest}m`:""}`;}
function elapsedMinutes(order:KitchenOrder,now=Date.now()){return Math.max(0,(now-order.startTime)/60000)}
function severity(order:KitchenOrder,now=Date.now()):Severity{const ratio=elapsedMinutes(order,now)/Math.max(1,order.estimatedMinutes);return ratio>=2?"severe":ratio>1?"delayed":ratio>=.8?"approaching":"normal"}
function inferredStation(name:string):PreparationStation{const value=name.toLowerCase();if(/burger|beef|chicken/.test(value))return "grill";if(/drink|coffee|tea|water|cola|juice|latte|ayran/.test(value))return "drinks";if(/cake|dessert|brownie|cookie|cheesecake/.test(value))return "dessert";return "kitchen"}
function kitchenItems(order:KitchenOrder){return order.items.filter(item=>{const station=item.station??inferredStation(item.name);return station==="kitchen"||station==="grill";});}

function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-[10000] flex items-center justify-center bg-black/75 p-4" role="dialog" aria-modal="true" aria-label={title} onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><div className="max-h-[85vh] w-full max-w-3xl overflow-y-auto rounded-2xl border border-white/10 bg-[#111511] p-5"><div className="mb-5 flex items-center"><h2 className="text-lg font-black">{title}</h2><button onClick={onClose} aria-label="Close" className="ml-auto rounded-lg p-2 text-white/40 hover:bg-white/10"><X size={18}/></button></div>{children}</div></div>}
function ElapsedTimer({order,now}:{order:KitchenOrder;now:number}){const state=severity(order,now);return <span className={`font-mono text-xs ${state==="severe"?"font-black text-red-300":state==="delayed"?"text-red-400":state==="approaching"?"text-amber-300":"text-white/45"}`}>{formatElapsedDuration(elapsedMinutes(order,now))}</span>}

function OrderCard({order,now,isNew,pending=false,onAdvance}:{order:KitchenOrder;now:number;isNew:boolean;pending?:boolean;onAdvance:(order:KitchenOrder,status:OrderStatus)=>void}){
  const current=STAGES.indexOf(order.status),demoNext=current<STAGES.length-1?STAGES[current+1]:null;
  const liveAction=order.databaseStatus ? getKitchenAction(order.databaseStatus) : null;
  const next:OrderStatus|null=liveAction ? ({confirmed:"received",preparing:"cooking",ready:"ready",completed:"completed"} as const)[liveAction.nextStatus as "confirmed"|"preparing"|"ready"|"completed"] : demoNext;
  const actionLabel=liveAction?.label ?? (next ? `Mark as ${COLUMNS.find(column=>column.id===next)?.label}` : "");
  const minutes=elapsedMinutes(order,now),state=severity(order,now),late=Math.max(0,minutes-order.estimatedMinutes),items=kitchenItems(order);
  const border=order.priority?"border-[#d7ff7a]/45":state==="severe"?"border-red-400/70":state==="delayed"?"border-red-500/40":state==="approaching"?"border-amber-400/35":"border-white/8";
  return <article className={`flex flex-col gap-3 rounded-2xl border bg-white/[0.03] p-4 transition-colors ${border} ${isNew?"ring-2 ring-[#d7ff7a]/60":""}`}>
    <div className="flex items-start justify-between gap-2"><div className="flex flex-wrap items-center gap-1.5">{isNew&&<span className="rounded-md bg-blue-400/15 px-1.5 py-0.5 text-[9px] font-black text-blue-300">New</span>}{order.priority&&<span className="flex items-center gap-1 rounded-md bg-[#d7ff7a] px-1.5 py-0.5 text-[9px] font-black uppercase text-[#17200f]"><Zap size={8}/>Priority</span>}{state!=="normal"&&state!=="approaching"&&<span className="flex items-center gap-1 rounded-md border border-red-500/20 bg-red-500/15 px-1.5 py-0.5 text-[9px] font-bold text-red-300"><AlertTriangle size={8}/>{state==="severe"?"Severely delayed":"Delayed"}</span>}<strong className="text-xl">#{order.number}</strong></div><ElapsedTimer order={order} now={now}/></div>
    {order.customer&&<p className="flex items-center gap-1 text-xs text-white/40"><Users size={10}/>{order.customer}</p>}
    <div className="space-y-2">{items.map((item,index)=><div key={`${item.name}-${index}`}><div className="flex items-start gap-2"><span className="grid size-6 shrink-0 place-items-center rounded-lg bg-white/10 text-[10px] font-bold">{item.qty}</span><span className="min-w-0 text-sm font-semibold">{item.name}</span></div>{item.customizations?.map(value=><p key={value} className="ml-8 mt-1 text-[11px] text-amber-300">• {value}</p>)}{item.notes&&<p className="ml-8 mt-1 text-[11px] text-amber-300">• {item.notes}</p>}{item.allergenWarnings?.map(value=><p key={value} className="ml-8 mt-1 rounded-md bg-red-500/15 px-2 py-1 text-[11px] font-bold text-red-300">Allergy: {value}</p>)}</div>)}</div>
    <div><div className="h-1 overflow-hidden rounded-full bg-white/5"><div className={`h-full rounded-full ${state==="severe"||state==="delayed"?"bg-red-500":state==="approaching"?"bg-amber-400":"bg-[#d7ff7a]"}`} style={{width:`${Math.min(100,(minutes/Math.max(1,order.estimatedMinutes))*100)}%`}}/></div><div className="mt-1 flex justify-between text-[10px] text-white/30"><span>Est. {formatElapsedDuration(order.estimatedMinutes)}</span>{late>0&&<span className={state==="severe"?"font-bold text-red-300":"text-red-400"}>{formatElapsedDuration(late)} late</span>}</div></div>
    {next&&order.status!=="completed"&&<button disabled={pending} onClick={()=>onAdvance(order,next)} className={`flex min-h-11 w-full items-center justify-center gap-1.5 rounded-xl border text-xs font-bold transition focus:outline-none focus:ring-2 focus:ring-[#d7ff7a]/50 disabled:cursor-wait disabled:opacity-50 ${next==="ready"?"border-[#d7ff7a]/20 bg-[#d7ff7a]/15 text-[#d7ff7a]":"border-white/8 bg-white/5 text-white/65 hover:bg-white/10 hover:text-white"}`}>{pending?"Updating…":<>{actionLabel}<ArrowRight size={12}/></>}</button>}
  </article>;
}

export default function KitchenDisplay({onNavigate:_onNavigate}:Props){
  const {updateKitchenOrderStatus}=useCart();
  const liveOrders=useKitchenOrders();const kitchenOrders=liveOrders.orders;
  const [search,setSearch]=useState("");const [filter,setFilter]=useState<"all"|"priority"|"delayed">("all");const [now,setNow]=useState(Date.now());const [historyOpen,setHistoryOpen]=useState(false);const [newIds,setNewIds]=useState<Set<string>>(new Set());
  const previousIds=useRef<Set<string>|null>(null);const ordersRef=useRef(kitchenOrders);const undoTokens=useRef(new Map<string,number>());ordersRef.current=kitchenOrders;
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[]);
  useEffect(()=>{if(liveOrders.error)toast.error(liveOrders.error)},[liveOrders.error]);
  useEffect(()=>{const ids=new Set(kitchenOrders.map(order=>order.id));if(previousIds.current){const incoming=kitchenOrders.filter(order=>!previousIds.current?.has(order.id)&&order.status==="received").map(order=>order.id);if(incoming.length){setNewIds(current=>new Set([...current,...incoming]));toast.info(`${incoming.length} new kitchen order${incoming.length>1?"s":""}.`);try{const AudioContextClass=window.AudioContext;const context=new AudioContextClass();const oscillator=context.createOscillator();const gain=context.createGain();oscillator.frequency.value=660;gain.gain.value=.025;oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.12);oscillator.addEventListener("ended",()=>context.close(),{once:true});}catch{/* Sound may be blocked or unavailable; visual feedback remains. */}window.setTimeout(()=>setNewIds(current=>{const next=new Set(current);incoming.forEach(id=>next.delete(id));return next}),6000)}}previousIds.current=ids},[kitchenOrders]);
  const activeOrders=useMemo(()=>kitchenOrders.filter(order=>order.status!=="completed"&&kitchenItems(order).length>0),[kitchenOrders]);
  const completedOrders=useMemo(()=>kitchenOrders.filter(order=>order.status==="completed"&&kitchenItems(order).length>0).sort((a,b)=>(b.completedAt??b.startTime)-(a.completedAt??a.startTime)),[kitchenOrders]);
  const recentCompleted=completedOrders.filter(order=>now-(order.completedAt??order.startTime)<=COMPLETED_KITCHEN_VISIBILITY_MS).slice(0,8);
  const hiddenCompleted=completedOrders.filter(order=>!recentCompleted.some(recent=>recent.id===order.id));
  const matches=(order:KitchenOrder)=>{const query=search.trim().toLowerCase();const delayed=severity(order,now)==="delayed"||severity(order,now)==="severe";return(!query||String(order.number).includes(query)||order.id.toLowerCase().includes(query)||(order.customer??"").toLowerCase().includes(query)||kitchenItems(order).some(item=>item.name.toLowerCase().includes(query)))&&(filter==="all"||filter==="priority"&&order.priority||filter==="delayed"&&delayed)};
  const getColumn=(status:OrderStatus)=>(status==="completed"?recentCompleted:activeOrders.filter(order=>order.status===status)).filter(matches).sort((a,b)=>Number(b.priority)-Number(a.priority)||(a.startTime-b.startTime));
  const today=new Date(now);today.setHours(0,0,0,0);const completedToday=completedOrders.filter(order=>(order.completedAt??order.startTime)>=today.getTime());const completedWithTime=completedToday.filter(order=>order.completedAt!==undefined);const averageSeconds=completedWithTime.length?completedWithTime.reduce((sum,order)=>sum+((order.completedAt??order.startTime)-order.startTime)/1000,0)/completedWithTime.length:0;const delayedCount=activeOrders.filter(order=>["delayed","severe"].includes(severity(order,now))).length;
  const advance=(order:KitchenOrder,status:OrderStatus)=>{if(!liveOrders.isDemo){void liveOrders.transition(order.id).then(ok=>{if(ok)toast.success(`Order #${order.number} updated.`)});return}const previous=order.status;const token=(undoTokens.current.get(order.id)??0)+1;undoTokens.current.set(order.id,token);updateKitchenOrderStatus(order.id,status);toast.success(`Order #${order.number} marked as ${COLUMNS.find(column=>column.id===status)?.label}.`,{duration:5000,action:{label:"Undo",onClick:()=>{const current=ordersRef.current.find(item=>item.id===order.id);if(current?.status===status&&undoTokens.current.get(order.id)===token){undoTokens.current.set(order.id,token+1);updateKitchenOrderStatus(order.id,previous);toast.success(`Order #${order.number} returned to ${COLUMNS.find(column=>column.id===previous)?.label}.`);}}}});};
  return <div className="flex min-h-screen flex-col bg-[#07090a] font-['DM_Sans'] text-[#f0f0eb]"><Toaster theme="dark" position="top-right"/><header className="flex flex-wrap items-center gap-4 border-b border-white/5 bg-[#07090a]/95 px-4 py-3 lg:px-6"><div className="flex items-center gap-3"><MorrowLogo variant="symbol" priority className="size-10 object-contain"/><div><h1 className="font-bold">Kitchen Display</h1><p className="text-xs text-white/40">Morrow Restaurant · {new Date(now).toLocaleTimeString()}</p></div></div><div className="ml-auto flex items-center">{[["Active",activeOrders.length,"text-orange-400"],["Done Today",liveOrders.isDemo?completedToday.length:liveOrders.doneToday,"text-emerald-400"],["Delayed",delayedCount,delayedCount?"text-red-400":"text-white/30"],["Average Time",completedWithTime.length?formatAverage(averageSeconds):"—","text-[#d7ff7a]"]].map(([label,value,color])=><div key={label} className="border-l border-white/5 px-3 text-center first:border-0 lg:px-4"><p className={`text-lg font-black ${color}`}>{value}</p><p className="text-[10px] text-white/30">{label}</p></div>)}</div></header>
    <div className="flex items-center gap-3 border-b border-white/5 bg-[#09090b] px-4 py-2.5 lg:px-6"><div className="flex max-w-xs flex-1 items-center gap-2 rounded-xl border border-white/8 bg-white/5 px-3 py-2"><Search size={14} className="text-white/30"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search orders or items…" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-white/25"/></div><div className="flex gap-1.5">{(["all","priority","delayed"] as const).map(value=><button key={value} onClick={()=>setFilter(value)} className={`rounded-xl px-3 py-2 text-xs font-semibold capitalize ${filter===value?"bg-[#d7ff7a] text-[#17200f]":"border border-white/8 bg-white/5 text-white/50"}`}>{value==="priority"&&<Zap size={10} className="mr-1 inline"/>}{value==="delayed"&&<AlertTriangle size={10} className="mr-1 inline"/>}{value}</button>)}</div><div className="ml-auto flex items-center gap-1.5 text-xs text-white/35"><RefreshCw size={12} className={liveOrders.connection==="connected"?"":"animate-spin [animation-duration:3s]"}/>{liveOrders.isDemo?"Demo":liveOrders.connection}</div></div>
    <div className="flex-1 overflow-x-auto"><div className="flex h-full min-w-max gap-3 p-4">{COLUMNS.map(column=>{const orders=getColumn(column.id);return <section key={column.id} className={`flex w-[290px] shrink-0 flex-col overflow-hidden rounded-2xl border border-t-2 border-white/6 bg-white/[0.02] ${colBorder[column.color]}`}><header className="sticky top-0 z-10 flex items-center justify-between border-b border-white/5 bg-[#0a0c0b] px-4 py-3"><span className={`flex items-center gap-1 rounded-lg border px-2.5 py-1 text-xs font-semibold ${colorBg[column.color]}`}>{column.icon}{column.label}</span><div className="flex items-center gap-2"><span className="grid size-5 place-items-center rounded-full bg-white/10 text-[10px] font-bold">{orders.length}</span>{orders.some(order=>order.priority)&&<Bell size={12} className="text-[#d7ff7a]"/>}</div></header><div className="flex max-h-[calc(100vh-176px)] flex-1 flex-col gap-2.5 overflow-y-auto p-3">{orders.length?orders.map(order=><OrderCard key={order.id} order={order} now={now} isNew={newIds.has(order.id)} pending={liveOrders.pendingId===order.id} onAdvance={advance}/>):<div className="py-12 text-center text-xs text-white/25">{column.empty}</div>}{column.id==="completed"&&hiddenCompleted.length>0&&<button onClick={()=>setHistoryOpen(true)} className="mt-auto min-h-10 rounded-xl border border-white/10 bg-white/5 text-xs font-bold text-white/55 hover:bg-white/10">View Completed History ({hiddenCompleted.length})</button>}</div></section>})}</div></div>
    {historyOpen&&<Modal title="Completed History" onClose={()=>setHistoryOpen(false)}><div className="space-y-2">{completedOrders.map(order=><div key={order.id} className="flex items-center justify-between rounded-xl border border-white/8 bg-white/[0.03] p-3"><div><strong>#{order.number}</strong><p className="text-xs text-white/35">{order.items.reduce((sum,item)=>sum+item.qty,0)} items · completed {new Date(order.completedAt??order.startTime).toLocaleString()}</p></div><span className="text-xs text-emerald-300">Completed</span></div>)}</div></Modal>}
  </div>;
}
