import type { SupportedLanguage } from "../config/languages";

export const customerTranslations = {
  en: {
    languageSelection: { eyebrow: "Welcome to Morrow", title: "Choose your language", subtitle: "Select your preferred language to continue", back: "Back to welcome", selected: "Selected" },
    serviceSelection: { eyebrow: "Service selection", title: "How would you like your order?", subtitle: "Choose your dining option to continue", dineInTitle: "Dine In", dineInDescription: "Enjoy your meal at the restaurant", takeAwayTitle: "Take Away", takeAwayDescription: "Take your order with you", back: "Back", selected: "Selected", footer: "Step 2 of 4 · Next: Menu" },
    cardTerminal: { title: "Use the card reader", instruction: "Tap, insert or swipe your card", helper: "Use the payment terminal beside the screen.", waiting: "Waiting for payment...", reading: "Card detected", processing: "Processing payment...", approved: "Payment approved", declined: "Payment declined", timeout: "Payment timed out", unavailable: "Card reader unavailable", cancelled: "Payment cancelled", cancel: "Cancel", tryAgain: "Try again", backToPaymentMethods: "Choose another payment method", declinedHelp: "Your payment could not be completed. Please try again or choose another payment method.", timeoutHelp: "No card was detected. You can try again or choose another payment method.", paid: "Amount paid" },
    orderConfirmation: { title: "Order confirmed", subtitle: "Your order has been sent to the kitchen", orderNumber: "Order number", printing: "Printing your receipt...", printed: "Receipt printed", printError: "Receipt could not be printed", instruction: "Please take your receipt and wait for your number to be called.", collectAtCounter: "Collect your order from the counter when your number is ready.", startNewOrder: "Start new order", retryPrint: "Retry print", continueWithoutReceipt: "Continue without receipt", returningIn: "Returning to the start screen in {seconds} seconds", errorHelp: "Your order was placed successfully. Please remember your order number." },
  },
  tr: {
    languageSelection: { eyebrow: "Morrow'a hoş geldiniz", title: "Dilinizi seçin", subtitle: "Devam etmek için tercih ettiğiniz dili seçin", back: "Karşılama ekranına dön", selected: "Seçildi" },
    serviceSelection: { eyebrow: "Servis seçimi", title: "Siparişinizi nasıl almak istersiniz?", subtitle: "Devam etmek için servis türünü seçin", dineInTitle: "Restoranda", dineInDescription: "Yemeğinizin keyfini restoranda çıkarın", takeAwayTitle: "Paket Servis", takeAwayDescription: "Siparişinizi yanınızda götürün", back: "Geri", selected: "Seçildi", footer: "4 adımın 2.'si · Sonraki: Menü" },
    cardTerminal: { title: "Kart okuyucuyu kullanın", instruction: "Kartınızı dokundurun, takın veya kaydırın", helper: "Ekranın yanındaki ödeme terminalini kullanın.", waiting: "Ödeme bekleniyor...", reading: "Kart algılandı", processing: "Ödeme işleniyor...", approved: "Ödeme onaylandı", declined: "Ödeme reddedildi", timeout: "Ödeme süresi doldu", unavailable: "Kart okuyucu kullanılamıyor", cancelled: "Ödeme iptal edildi", cancel: "İptal", tryAgain: "Tekrar deneyin", backToPaymentMethods: "Başka bir ödeme yöntemi seçin", declinedHelp: "Ödemeniz tamamlanamadı. Lütfen tekrar deneyin veya başka bir ödeme yöntemi seçin.", timeoutHelp: "Kart algılanmadı. Tekrar deneyebilir veya başka bir ödeme yöntemi seçebilirsiniz.", paid: "Ödenen tutar" },
    orderConfirmation: { title: "Sipariş onaylandı", subtitle: "Siparişiniz mutfağa gönderildi", orderNumber: "Sipariş numarası", printing: "Fişiniz yazdırılıyor...", printed: "Fiş yazdırıldı", printError: "Fiş yazdırılamadı", instruction: "Lütfen fişinizi alın ve numaranızın çağrılmasını bekleyin.", collectAtCounter: "Numaranız hazır olduğunda siparişinizi tezgahtan alın.", startNewOrder: "Yeni sipariş başlat", retryPrint: "Tekrar yazdır", continueWithoutReceipt: "Fişsiz devam et", returningIn: "{seconds} saniye içinde başlangıç ekranına dönülüyor", errorHelp: "Siparişiniz başarıyla verildi. Lütfen sipariş numaranızı unutmayın." },
  },
  ar: {
    languageSelection: { eyebrow: "مرحباً بكم في مورو", title: "اختر لغتك", subtitle: "اختر اللغة التي تفضلها للمتابعة", back: "العودة إلى شاشة الترحيب", selected: "تم الاختيار" },
    serviceSelection: { eyebrow: "اختيار الخدمة", title: "كيف ترغب باستلام طلبك؟", subtitle: "اختر نوع الخدمة للمتابعة", dineInTitle: "تناول الطعام هنا", dineInDescription: "استمتع بوجبتك داخل المطعم", takeAwayTitle: "طلب خارجي", takeAwayDescription: "خذ طلبك معك", back: "رجوع", selected: "تم الاختيار", footer: "الخطوة 2 من 4 · التالي: القائمة" },
    cardTerminal: { title: "استخدم قارئ البطاقة", instruction: "قرّب بطاقتك أو أدخلها أو مرّرها", helper: "استخدم جهاز الدفع الموجود بجانب الشاشة.", waiting: "بانتظار الدفع...", reading: "تم اكتشاف البطاقة", processing: "جارٍ معالجة الدفع...", approved: "تمت الموافقة على الدفع", declined: "تم رفض الدفع", timeout: "انتهت مهلة الدفع", unavailable: "قارئ البطاقة غير متاح", cancelled: "تم إلغاء الدفع", cancel: "إلغاء", tryAgain: "حاول مرة أخرى", backToPaymentMethods: "اختر طريقة دفع أخرى", declinedHelp: "تعذر إتمام عملية الدفع. يرجى المحاولة مرة أخرى أو اختيار طريقة دفع أخرى.", timeoutHelp: "لم يتم اكتشاف بطاقة. يمكنك المحاولة مرة أخرى أو اختيار طريقة دفع أخرى.", paid: "المبلغ المدفوع" },
    orderConfirmation: { title: "تم تأكيد الطلب", subtitle: "تم إرسال طلبك إلى المطبخ", orderNumber: "رقم الطلب", printing: "جارٍ طباعة إيصالك...", printed: "تمت طباعة الإيصال", printError: "تعذرت طباعة الإيصال", instruction: "يرجى أخذ إيصالك وانتظار مناداة رقمك.", collectAtCounter: "استلم طلبك من المنضدة عندما يصبح رقمك جاهزاً.", startNewOrder: "ابدأ طلباً جديداً", retryPrint: "إعادة الطباعة", continueWithoutReceipt: "المتابعة دون إيصال", returningIn: "العودة إلى شاشة البداية خلال {seconds} ثانية", errorHelp: "تم تقديم طلبك بنجاح. يرجى تذكر رقم طلبك." },
  },
} as const;

export function getCustomerTranslation(language: SupportedLanguage) {
  return customerTranslations[language] ?? customerTranslations.en;
}
