import type { SupportedLanguage } from "../config/languages";

export const customerTranslations = {
  en: {
    languageSelection: { eyebrow: "Welcome to cangujet", title: "Choose your language", subtitle: "Select your preferred language to continue", back: "Back to welcome", selected: "Selected" },
    serviceSelection: { eyebrow: "Service selection", title: "How would you like your order?", subtitle: "Choose your dining option to continue", dineInTitle: "Dine In", dineInDescription: "Enjoy your meal at the restaurant", takeAwayTitle: "Take Away", takeAwayDescription: "Take your order with you", back: "Back", selected: "Selected", footer: "Step 2 of 4 · Next: Menu" },
    cardTerminal: { title: "Use the card reader", instruction: "Tap, insert or swipe your card", helper: "Use the payment terminal beside the screen.", waiting: "Waiting for payment...", reading: "Card detected", processing: "Processing payment...", approved: "Payment approved", declined: "Payment declined", timeout: "Payment timed out", unavailable: "Card reader unavailable", cancelled: "Payment cancelled", cancel: "Cancel", tryAgain: "Try again", backToPaymentMethods: "Choose another payment method", declinedHelp: "Your payment could not be completed. Please try again or choose another payment method.", timeoutHelp: "No card was detected. You can try again or choose another payment method.", paid: "Amount paid" },
    orderConfirmation: { title: "Order confirmed", subtitle: "Your order has been sent to the kitchen", orderNumber: "Order number", printing: "Printing your receipt...", printed: "Receipt printed", printError: "Receipt could not be printed", instruction: "Please take your receipt and wait for your number to be called.", collectAtCounter: "Collect your order from the counter when your number is ready.", startNewOrder: "Start new order", retryPrint: "Retry print", continueWithoutReceipt: "Continue without receipt", returningIn: "Returning to the start screen in {seconds} seconds", errorHelp: "Your order was placed successfully. Please remember your order number." },
  },
  tr: {
    languageSelection: { eyebrow: "cangujet'a hoş geldiniz", title: "Dilinizi seçin", subtitle: "Devam etmek için tercih ettiğiniz dili seçin", back: "Karşılama ekranına dön", selected: "Seçildi" },
    serviceSelection: { eyebrow: "Servis seçimi", title: "Siparişinizi nasıl almak istersiniz?", subtitle: "Devam etmek için servis türünü seçin", dineInTitle: "Restoranda", dineInDescription: "Yemeğinizin keyfini restoranda çıkarın", takeAwayTitle: "Paket Servis", takeAwayDescription: "Siparişinizi yanınızda götürün", back: "Geri", selected: "Seçildi", footer: "4 adımın 2.'si · Sonraki: Menü" },
    cardTerminal: { title: "Kart okuyucuyu kullanın", instruction: "Kartınızı dokundurun, takın veya kaydırın", helper: "Ekranın yanındaki ödeme terminalini kullanın.", waiting: "Ödeme bekleniyor...", reading: "Kart algılandı", processing: "Ödeme işleniyor...", approved: "Ödeme onaylandı", declined: "Ödeme reddedildi", timeout: "Ödeme süresi doldu", unavailable: "Kart okuyucu kullanılamıyor", cancelled: "Ödeme iptal edildi", cancel: "İptal", tryAgain: "Tekrar deneyin", backToPaymentMethods: "Başka bir ödeme yöntemi seçin", declinedHelp: "Ödemeniz tamamlanamadı. Lütfen tekrar deneyin veya başka bir ödeme yöntemi seçin.", timeoutHelp: "Kart algılanmadı. Tekrar deneyebilir veya başka bir ödeme yöntemi seçebilirsiniz.", paid: "Ödenen tutar" },
    orderConfirmation: { title: "Sipariş onaylandı", subtitle: "Siparişiniz mutfağa gönderildi", orderNumber: "Sipariş numarası", printing: "Fişiniz yazdırılıyor...", printed: "Fiş yazdırıldı", printError: "Fiş yazdırılamadı", instruction: "Lütfen fişinizi alın ve numaranızın çağrılmasını bekleyin.", collectAtCounter: "Numaranız hazır olduğunda siparişinizi tezgahtan alın.", startNewOrder: "Yeni sipariş başlat", retryPrint: "Tekrar yazdır", continueWithoutReceipt: "Fişsiz devam et", returningIn: "{seconds} saniye içinde başlangıç ekranına dönülüyor", errorHelp: "Siparişiniz başarıyla verildi. Lütfen sipariş numaranızı unutmayın." },
  },
} as const;

export function getCustomerTranslation(language: SupportedLanguage) {
  return customerTranslations[language] ?? customerTranslations.en;
}
