import { emailLayout } from "./emailLayout.ts";
import { escapeHtml, plainTextValue } from "../utils/escapeHtml.ts";
import type { DailyReportData } from "../data/reportData.ts";

export function buildDailySalesReportEmail(data:DailyReportData){
  const topProducts=data.topProducts.slice(0,3);
  const metric=(label:string,value:string|number)=>`<td width="50%" style="padding:13px;vertical-align:top;"><div style="font-size:11px;line-height:16px;color:#9CA39A;">${escapeHtml(label)}</div><div style="padding-top:5px;font-size:23px;line-height:28px;font-weight:800;color:#FFFFFF;">${escapeHtml(String(value))}</div></td>`;
  const comparison=data.comparison?`<div style="margin-top:18px;padding:13px 16px;border-radius:10px;background:#1A1D18;font-size:13px;line-height:20px;color:#FFFFFF;"><span style="color:#9CA39A;">Compared with yesterday:</span>&nbsp; Sales ${escapeHtml(data.comparison.sales)} &nbsp;·&nbsp; Orders ${escapeHtml(data.comparison.orders)}</div>`:"";
  const products=topProducts.length?`<div style="margin-top:28px;"><div style="font-size:12px;font-weight:800;letter-spacing:1px;color:#D7FB69;">TOP PRODUCTS</div>${topProducts.map((product,index)=>`<div style="padding:13px 0;border-bottom:1px solid #292c27;font-size:14px;line-height:20px;color:#FFFFFF;"><strong>${index+1}. ${escapeHtml(product.name)}</strong><br><span style="font-size:12px;color:#9CA39A;">${product.quantity} sold · ${escapeHtml(product.sales)}</span></div>`).join("")}</div>`:"";
  const payment=`<div style="margin-top:25px;"><div style="font-size:12px;font-weight:800;letter-spacing:1px;color:#D7FB69;">CAPTURED PAYMENTS</div><div style="padding-top:9px;font-size:14px;line-height:21px;color:#FFFFFF;">${data.payments.length?data.payments.map(item=>`${escapeHtml(item.label)} ${item.count}${item.total?` · ${escapeHtml(item.total)}`:""}`).join(" &nbsp;·&nbsp; "):"No captured payments"}</div></div>`;
  const statuses=`<div style="margin-top:22px;"><div style="font-size:12px;font-weight:800;letter-spacing:1px;color:#D7FB69;">ORDER STATUS</div><div style="padding-top:9px;font-size:14px;line-height:21px;color:#FFFFFF;">Submitted ${data.submittedOrders} &nbsp;·&nbsp; Completed ${data.completedOrders} &nbsp;·&nbsp; Cancelled ${data.cancelledOrders}</div></div>`;
  const source=data.sources.length?`<div style="margin-top:22px;"><div style="font-size:12px;font-weight:800;letter-spacing:1px;color:#D7FB69;">ORDER SOURCES</div><div style="padding-top:9px;font-size:14px;line-height:21px;color:#FFFFFF;">${data.sources.length===1?`All orders came from ${escapeHtml(data.sources[0].label)}.`:data.sources.map(item=>`${escapeHtml(item.label)} ${item.count}`).join(" &nbsp;·&nbsp; ")}</div></div>`:"";
  const attention=data.attention.length?`<div style="margin-top:24px;padding:15px 17px;border-left:3px solid #F0B35A;border-radius:8px;background:#1A1D18;"><div style="font-size:12px;font-weight:800;color:#F0B35A;">NEEDS ATTENTION</div><div style="padding-top:7px;font-size:13px;line-height:20px;color:#FFFFFF;">${data.attention.map(escapeHtml).join("<br>")}</div></div>`:"";
  const content=`<h1 style="margin:0;font-size:28px;line-height:34px;color:#FFFFFF;">Daily Sales Report</h1><div style="padding-top:8px;font-size:14px;line-height:21px;color:#9CA39A;">${escapeHtml(data.branchName)} — ${escapeHtml(data.localDate)}</div>
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-top:24px;border:1px solid #292c27;border-radius:12px;background:#1A1D18;"><tr>${metric("Total Sales (Paid)",data.paidSales)}${metric("Gross Order Value",data.grossSales)}</tr><tr>${metric("Total Orders",data.totalOrders)}${metric("Paid Orders",data.paidOrders)}</tr><tr>${metric("Average Order Value",data.averageOrderValue)}${metric("Cancelled Orders",data.cancelledOrders)}</tr></table>
  ${comparison}${products}${payment}${statuses}${source}${attention}<div style="padding-top:28px;font-size:11px;color:#737970;">Generated automatically by cangujet.</div>`;
  const text=[`cangujet\nDaily Sales Report\n${plainTextValue(data.branchName)} — ${plainTextValue(data.localDate)}`,`Total Sales (Paid): ${plainTextValue(data.paidSales)}\nGross Order Value: ${plainTextValue(data.grossSales)}\nTotal Orders: ${data.totalOrders}\nAverage Order Value: ${plainTextValue(data.averageOrderValue)}\nPaid Orders: ${data.paidOrders}`,`Order Status:\nSubmitted ${data.submittedOrders} · Completed ${data.completedOrders} · Cancelled ${data.cancelledOrders}`,data.comparison?`Compared with yesterday:\nSales ${data.comparison.sales} · Orders ${data.comparison.orders}`:"",topProducts.length?`Top Products:\n${topProducts.map((product,index)=>`${index+1}. ${plainTextValue(product.name)} — ${product.quantity} sold · ${plainTextValue(product.sales)}`).join("\n")}`:"",`Captured Payments:\n${data.payments.length?data.payments.map(item=>`${item.label} ${item.count}${item.total?` · ${plainTextValue(item.total)}`:""}`).join(" · "):"No captured payments"}`,data.sources.length?`Order Sources:\n${data.sources.length===1?`All orders came from ${plainTextValue(data.sources[0].label)}.`:data.sources.map(item=>`${item.label} ${item.count}`).join(" · ")}`:"",data.attention.length?`Needs Attention:\n${data.attention.map(plainTextValue).join("\n")}`:"","Generated automatically by cangujet."].filter(Boolean).join("\n\n");
  return{subject:`cangujet — Daily Sales Report — ${data.localDate}`,html:emailLayout({content,branchName:data.branchName,sent:data.localDate,preheader:`Daily sales for ${data.branchName}`}),text};
}
