// Generated by scripts/generate-menu-image-manifest.mjs. Do not edit manually.
export interface MenuImageEntry { id: string; name: string; category: string; image: string; filename: string; sourcePath: string; productId?: string; needsConfiguration: boolean }
export const cashierMenuImageManifest = [
  {
    "id": "burgers-burger-2",
    "name": "Burger",
    "category": "Burgers",
    "image": "/images/products/burger%20(2).png",
    "filename": "burger (2).png",
    "sourcePath": "public/images/products/burger (2).png",
    "productId": "burger-beef-classic",
    "needsConfiguration": false
  },
  {
    "id": "burgers-burger-3",
    "name": "Burger",
    "category": "Burgers",
    "image": "/images/products/burger%20(3).png",
    "filename": "burger (3).png",
    "sourcePath": "public/images/products/burger (3).png",
    "productId": "burger-chicken-spicy",
    "needsConfiguration": false
  },
  {
    "id": "burgers-burger-4",
    "name": "Burger",
    "category": "Burgers",
    "image": "/images/products/burger%20(4).png",
    "filename": "burger (4).png",
    "sourcePath": "public/images/products/burger (4).png",
    "productId": "burger-veggie",
    "needsConfiguration": false
  },
  {
    "id": "burgers-burger-5",
    "name": "Burger",
    "category": "Burgers",
    "image": "/images/products/burger%20(5).png",
    "filename": "burger (5).png",
    "sourcePath": "public/images/products/burger (5).png",
    "productId": "burger-turkey-light",
    "needsConfiguration": false
  },
  {
    "id": "burgers-burger",
    "name": "Burger",
    "category": "Burgers",
    "image": "/images/products/burger.png",
    "filename": "burger.png",
    "sourcePath": "public/images/products/burger.png",
    "needsConfiguration": true
  },
  {
    "id": "sides-chicken-2",
    "name": "Chicken",
    "category": "Sides",
    "image": "/images/products/chicken%20(2).png",
    "filename": "chicken (2).png",
    "sourcePath": "public/images/products/chicken (2).png",
    "productId": "side-rosemary-fries",
    "needsConfiguration": false
  },
  {
    "id": "sides-chicken-3",
    "name": "Chicken",
    "category": "Sides",
    "image": "/images/products/chicken%20(3).png",
    "filename": "chicken (3).png",
    "sourcePath": "public/images/products/chicken (3).png",
    "productId": "side-sweet-potato",
    "needsConfiguration": false
  },
  {
    "id": "sides-chicken-4",
    "name": "Chicken",
    "category": "Sides",
    "image": "/images/products/chicken%20(4).png",
    "filename": "chicken (4).png",
    "sourcePath": "public/images/products/chicken (4).png",
    "productId": "side-green-salad",
    "needsConfiguration": false
  },
  {
    "id": "sides-chicken",
    "name": "Chicken",
    "category": "Sides",
    "image": "/images/products/chicken.png",
    "filename": "chicken.png",
    "sourcePath": "public/images/products/chicken.png",
    "productId": "side-mozzarella",
    "needsConfiguration": false
  },
  {
    "id": "drinks-coffee-2",
    "name": "Coffee",
    "category": "Drinks",
    "image": "/images/products/coffee%20(2).png",
    "filename": "coffee (2).png",
    "sourcePath": "public/images/products/coffee (2).png",
    "productId": "drink-americano",
    "needsConfiguration": false
  },
  {
    "id": "drinks-coffee-3",
    "name": "Coffee",
    "category": "Drinks",
    "image": "/images/products/coffee%20(3).png",
    "filename": "coffee (3).png",
    "sourcePath": "public/images/products/coffee (3).png",
    "productId": "drink-cappuccino",
    "needsConfiguration": false
  },
  {
    "id": "drinks-coffee-4",
    "name": "Coffee",
    "category": "Drinks",
    "image": "/images/products/coffee%20(4).png",
    "filename": "coffee (4).png",
    "sourcePath": "public/images/products/coffee (4).png",
    "productId": "drink-hot-mocha",
    "needsConfiguration": false
  },
  {
    "id": "drinks-coffee-5",
    "name": "Coffee",
    "category": "Drinks",
    "image": "/images/products/coffee%20(5).png",
    "filename": "coffee (5).png",
    "sourcePath": "public/images/products/coffee (5).png",
    "productId": "drink-herbal-tea",
    "needsConfiguration": false
  },
  {
    "id": "drinks-coffee-6",
    "name": "Coffee",
    "category": "Drinks",
    "image": "/images/products/coffee%20(6).png",
    "filename": "coffee (6).png",
    "sourcePath": "public/images/products/coffee (6).png",
    "needsConfiguration": true
  },
  {
    "id": "drinks-coffee",
    "name": "Coffee",
    "category": "Drinks",
    "image": "/images/products/coffee.png",
    "filename": "coffee.png",
    "sourcePath": "public/images/products/coffee.png",
    "needsConfiguration": true
  },
  {
    "id": "desserts-desserts-2",
    "name": "Desserts",
    "category": "Desserts",
    "image": "/images/products/desserts%20(2).png",
    "filename": "desserts (2).png",
    "sourcePath": "public/images/products/desserts (2).png",
    "productId": "dessert-chocolate-cake",
    "needsConfiguration": false
  },
  {
    "id": "desserts-desserts-4",
    "name": "Desserts",
    "category": "Desserts",
    "image": "/images/products/desserts%20(4).png",
    "filename": "desserts (4).png",
    "sourcePath": "public/images/products/desserts (4).png",
    "productId": "dessert-cheesecake",
    "needsConfiguration": false
  },
  {
    "id": "desserts-desserts-5",
    "name": "Desserts",
    "category": "Desserts",
    "image": "/images/products/desserts%20(5).png",
    "filename": "desserts (5).png",
    "sourcePath": "public/images/products/desserts (5).png",
    "productId": "dessert-vegan-chia",
    "needsConfiguration": false
  },
  {
    "id": "desserts-desserts",
    "name": "Desserts",
    "category": "Desserts",
    "image": "/images/products/desserts.png",
    "filename": "desserts.png",
    "sourcePath": "public/images/products/desserts.png",
    "productId": "dessert-yogurt-fruit",
    "needsConfiguration": false
  },
  {
    "id": "drinks-drink-2",
    "name": "Drink",
    "category": "Drinks",
    "image": "/images/products/drink%20(2).png",
    "filename": "drink (2).png",
    "sourcePath": "public/images/products/drink (2).png",
    "productId": "drink-cold-brew",
    "needsConfiguration": false
  },
  {
    "id": "drinks-drink-3",
    "name": "Drink",
    "category": "Drinks",
    "image": "/images/products/drink%20(3).png",
    "filename": "drink (3).png",
    "sourcePath": "public/images/products/drink (3).png",
    "productId": "drink-iced-matcha",
    "needsConfiguration": false
  },
  {
    "id": "drinks-drink-4",
    "name": "Drink",
    "category": "Drinks",
    "image": "/images/products/drink%20(4).png",
    "filename": "drink (4).png",
    "sourcePath": "public/images/products/drink (4).png",
    "productId": "drink-lemon-mint",
    "needsConfiguration": false
  },
  {
    "id": "drinks-drink-5",
    "name": "Drink",
    "category": "Drinks",
    "image": "/images/products/drink%20(5).png",
    "filename": "drink (5).png",
    "sourcePath": "public/images/products/drink (5).png",
    "productId": "drink-yogurt-mint",
    "needsConfiguration": false
  },
  {
    "id": "drinks-drink-6",
    "name": "Drink",
    "category": "Drinks",
    "image": "/images/products/drink%20(6).png",
    "filename": "drink (6).png",
    "sourcePath": "public/images/products/drink (6).png",
    "productId": "drink-water",
    "needsConfiguration": false
  },
  {
    "id": "drinks-drink-7",
    "name": "Drink",
    "category": "Drinks",
    "image": "/images/products/drink%20(7).png",
    "filename": "drink (7).png",
    "sourcePath": "public/images/products/drink (7).png",
    "needsConfiguration": true
  },
  {
    "id": "drinks-drink-8",
    "name": "Drink",
    "category": "Drinks",
    "image": "/images/products/drink%20(8).png",
    "filename": "drink (8).png",
    "sourcePath": "public/images/products/drink (8).png",
    "needsConfiguration": true
  },
  {
    "id": "drinks-drink-9",
    "name": "Drink",
    "category": "Drinks",
    "image": "/images/products/drink%20(9).png",
    "filename": "drink (9).png",
    "sourcePath": "public/images/products/drink (9).png",
    "needsConfiguration": true
  },
  {
    "id": "drinks-drink-10",
    "name": "Drink",
    "category": "Drinks",
    "image": "/images/products/drink%20(10).png",
    "filename": "drink (10).png",
    "sourcePath": "public/images/products/drink (10).png",
    "needsConfiguration": true
  },
  {
    "id": "drinks-drink",
    "name": "Drink",
    "category": "Drinks",
    "image": "/images/products/drink.png",
    "filename": "drink.png",
    "sourcePath": "public/images/products/drink.png",
    "needsConfiguration": true
  },
  {
    "id": "pasta-pasta-2",
    "name": "Pasta",
    "category": "Pasta",
    "image": "/images/products/pasta%20(2).png",
    "filename": "pasta (2).png",
    "sourcePath": "public/images/products/pasta (2).png",
    "productId": "pasta-chicken-alfredo",
    "needsConfiguration": false
  },
  {
    "id": "pasta-pasta-3",
    "name": "Pasta",
    "category": "Pasta",
    "image": "/images/products/pasta%20(3).png",
    "filename": "pasta (3).png",
    "sourcePath": "public/images/products/pasta (3).png",
    "productId": "pasta-arrabbiata",
    "needsConfiguration": false
  },
  {
    "id": "pasta-pasta-4",
    "name": "Pasta",
    "category": "Pasta",
    "image": "/images/products/pasta%20(4).png",
    "filename": "pasta (4).png",
    "sourcePath": "public/images/products/pasta (4).png",
    "productId": "pasta-beef-bolognese",
    "needsConfiguration": false
  },
  {
    "id": "pasta-pasta-5",
    "name": "Pasta",
    "category": "Pasta",
    "image": "/images/products/pasta%20(5).png",
    "filename": "pasta (5).png",
    "sourcePath": "public/images/products/pasta (5).png",
    "productId": "pasta-salmon-lemon",
    "needsConfiguration": false
  },
  {
    "id": "pasta-pasta",
    "name": "Pasta",
    "category": "Pasta",
    "image": "/images/products/pasta.png",
    "filename": "pasta.png",
    "sourcePath": "public/images/products/pasta.png",
    "needsConfiguration": true
  },
  {
    "id": "pizza-pizza-2",
    "name": "Pizza",
    "category": "Pizza",
    "image": "/images/products/pizza%20(2).png",
    "filename": "pizza (2).png",
    "sourcePath": "public/images/products/pizza (2).png",
    "productId": "pizza-margherita",
    "needsConfiguration": false
  },
  {
    "id": "pizza-pizza-3",
    "name": "Pizza",
    "category": "Pizza",
    "image": "/images/products/pizza%20(3).png",
    "filename": "pizza (3).png",
    "sourcePath": "public/images/products/pizza (3).png",
    "productId": "pizza-chicken-bbq",
    "needsConfiguration": false
  },
  {
    "id": "pizza-pizza-4",
    "name": "Pizza",
    "category": "Pizza",
    "image": "/images/products/pizza%20(4).png",
    "filename": "pizza (4).png",
    "sourcePath": "public/images/products/pizza (4).png",
    "productId": "pizza-vegan",
    "needsConfiguration": false
  },
  {
    "id": "pizza-pizza",
    "name": "Pizza",
    "category": "Pizza",
    "image": "/images/products/pizza.png",
    "filename": "pizza.png",
    "sourcePath": "public/images/products/pizza.png",
    "productId": "pizza-beef-spicy",
    "needsConfiguration": false
  },
  {
    "id": "bowls-salads-2",
    "name": "Salads",
    "category": "Bowls",
    "image": "/images/products/salads%20(2).png",
    "filename": "salads (2).png",
    "sourcePath": "public/images/products/salads (2).png",
    "productId": "bowl-chicken-protein",
    "needsConfiguration": false
  },
  {
    "id": "bowls-salads-3",
    "name": "Salads",
    "category": "Bowls",
    "image": "/images/products/salads%20(3).png",
    "filename": "salads (3).png",
    "sourcePath": "public/images/products/salads (3).png",
    "productId": "bowl-vegan-zen",
    "needsConfiguration": false
  },
  {
    "id": "bowls-salads-4",
    "name": "Salads",
    "category": "Bowls",
    "image": "/images/products/salads%20(4).png",
    "filename": "salads (4).png",
    "sourcePath": "public/images/products/salads (4).png",
    "productId": "salad-tuna",
    "needsConfiguration": false
  },
  {
    "id": "bowls-salads-5",
    "name": "Salads",
    "category": "Bowls",
    "image": "/images/products/salads%20(5).png",
    "filename": "salads (5).png",
    "sourcePath": "public/images/products/salads (5).png",
    "productId": "salad-lentil",
    "needsConfiguration": false
  },
  {
    "id": "bowls-salads",
    "name": "Salads",
    "category": "Bowls",
    "image": "/images/products/salads.png",
    "filename": "salads.png",
    "sourcePath": "public/images/products/salads.png",
    "needsConfiguration": true
  }
] as const satisfies readonly MenuImageEntry[];
export const cashierMenuCategories = ["Burgers","Sides","Drinks","Desserts","Pasta","Pizza","Bowls"] as const;
export const cashierMenuImageReport = {
  "products": 43,
  "uniqueImages": 43,
  "matchedProducts": 33,
  "missingImages": 0,
  "duplicateImageMappings": 0,
  "duplicateIds": 0,
  "unconfiguredImages": 10
} as const;
export const cashierMenuProductsMissingImages = [] as const;
