import type { SupportedLanguage } from "../../config/languages";
export const noriCopy: Record<SupportedLanguage, {
  title: string; description: string; chat: string; chatDescription: string; startChat: string; voice: string; voiceDescription: string; startVoice: string;
  back: string; end: string; switchText: string; switchVoice: string; privacy: string; voiceResponses: string; tap: string; permission: string; listening: string; thinking: string; speaking: string; noSpeech: string; denied: string; unsupported: string; error: string; heard: string; send: string; tryAgain: string;
}> = {
  en: { title: "How would you like to talk to Nori?", description: "Choose how you would like help finding your meal.", chat: "Chat with Nori", chatDescription: "Type your questions and receive recommendations.", startChat: "Start Chat", voice: "Talk to Nori", voiceDescription: "Speak naturally and hear Nori’s response.", startVoice: "Start Voice", back: "Back", end: "End Conversation", switchText: "Switch to Text Chat", switchVoice: "Voice mode", privacy: "Your voice is used only to understand your request during this conversation.", voiceResponses: "Voice responses", tap: "Tap the microphone to speak", permission: "Allow microphone access to talk to Nori", listening: "I’m listening…", thinking: "Nori is thinking…", speaking: "Nori is responding…", noSpeech: "I didn’t hear anything. Please try again.", denied: "Microphone access is blocked. Enable microphone access or continue using text chat.", unsupported: "Voice conversation isn’t available on this kiosk.", error: "Something went wrong. Please try again.", heard: "I heard:", send: "Send", tryAgain: "Try Again" },
  tr: { title: "Nori ile nasıl konuşmak istersiniz?", description: "Yemeğinizi bulmak için nasıl yardım almak istediğinizi seçin.", chat: "Nori ile yazış", chatDescription: "Sorularınızı yazın ve öneriler alın.", startChat: "Sohbeti Başlat", voice: "Nori ile konuş", voiceDescription: "Doğal biçimde konuşun ve Nori’nin yanıtını dinleyin.", startVoice: "Sesli Görüşmeyi Başlat", back: "Geri", end: "Görüşmeyi Bitir", switchText: "Yazılı Sohbete Geç", switchVoice: "Sesli mod", privacy: "Sesiniz yalnızca bu görüşme sırasında isteğinizi anlamak için kullanılır.", voiceResponses: "Sesli yanıtlar", tap: "Konuşmak için mikrofona dokunun", permission: "Nori ile konuşmak için mikrofon erişimine izin verin", listening: "Sizi dinliyorum…", thinking: "Nori düşünüyor…", speaking: "Nori yanıtlıyor…", noSpeech: "Sesinizi duyamadım. Lütfen tekrar deneyin.", denied: "Mikrofon erişimi engellendi. Erişimi etkinleştirin veya yazılı sohbeti kullanın.", unsupported: "Bu kioskte sesli görüşme desteklenmiyor.", error: "Bir sorun oluştu. Lütfen tekrar deneyin.", heard: "Duyduğum:", send: "Gönder", tryAgain: "Tekrar Dene" },
  ar: { title: "كيف ترغب بالتحدث مع نوري؟", description: "اختر الطريقة التي تريد استخدامها للحصول على المساعدة في اختيار وجبتك.", chat: "الدردشة مع نوري", chatDescription: "اكتب أسئلتك واحصل على اقتراحات مناسبة.", startChat: "ابدأ الدردشة", voice: "تحدث مع نوري", voiceDescription: "تحدث بشكل طبيعي واستمع إلى رد نوري.", startVoice: "ابدأ المحادثة الصوتية", back: "رجوع", end: "إنهاء المحادثة", switchText: "الانتقال إلى الدردشة النصية", switchVoice: "الوضع الصوتي", privacy: "يُستخدم صوتك فقط لفهم طلبك أثناء هذه المحادثة.", voiceResponses: "الردود الصوتية", tap: "اضغط على الميكروفون للتحدث", permission: "اسمح بالوصول إلى الميكروفون للتحدث مع نوري", listening: "أنا أستمع…", thinking: "نوري يفكر…", speaking: "نوري يجيب…", noSpeech: "لم أسمع شيئًا. حاول مرة أخرى.", denied: "الوصول إلى الميكروفون محظور. فعّله أو تابع باستخدام الدردشة النصية.", unsupported: "المحادثة الصوتية غير متاحة على هذا الكشك.", error: "حدث خطأ. حاول مرة أخرى.", heard: "سمعت:", send: "إرسال", tryAgain: "حاول مرة أخرى" },
};
