import { useState } from "react";
import { ArrowLeft, Mic, Send, Sparkles, X } from "lucide-react";
import { useNoriConversation } from "../../context/NoriConversationContext";
import { useLanguage } from "../../context/LanguageContext";
import { noriCopy } from "./noriCopy";
export default function NoriTextChat({ onBack, onVoice, onEnd }: { onBack: () => void; onVoice: () => void; onEnd: () => void }) {
  const { language, direction } = useLanguage(); const text = noriCopy[language]; const { messages, isProcessing, sendMessage } = useNoriConversation(); const [input, setInput] = useState("");
  const submit = () => { const value = input.trim(); if (!value || isProcessing) return; setInput(""); void sendMessage(value); };
  return <main dir={direction} className="flex min-h-[100dvh] flex-col bg-[#080b08] font-['DM_Sans'] text-white"><header className="flex items-center gap-3 border-b border-white/8 p-4 sm:p-6"><button type="button" onClick={onBack} aria-label={text.back} className="grid size-11 place-items-center rounded-xl bg-white/5"><ArrowLeft/></button><span className="grid size-11 place-items-center rounded-xl bg-[#D7FB69]/10 text-[#D7FB69]"><Sparkles/></span><div><h1 className="font-bold">Nori AI</h1><p className="text-xs text-white/40">{text.chat}</p></div><div className="ms-auto flex gap-2"><button type="button" onClick={onVoice} aria-label={text.switchVoice} className="flex min-h-11 items-center gap-2 rounded-xl bg-white/5 px-3 text-xs"><Mic size={16}/>{text.switchVoice}</button><button type="button" onClick={onEnd} aria-label={text.end} className="grid size-11 place-items-center rounded-xl bg-white/5"><X/></button></div></header><section className="mx-auto flex w-full max-w-3xl flex-1 flex-col gap-3 overflow-y-auto p-5">{messages.map(message => <div key={message.id} className={`max-w-[85%] rounded-2xl px-5 py-4 leading-6 ${message.sender === "user" ? "ms-auto bg-[#D7FB69] text-[#17200f]" : "me-auto border border-white/10 bg-white/5"}`}>{message.text}</div>)}{isProcessing && <div className="me-auto rounded-2xl bg-white/5 px-5 py-4 text-white/45">{text.thinking}</div>}</section><footer className="border-t border-white/8 p-4"><div className="mx-auto flex max-w-3xl gap-2"><textarea value={input} disabled={isProcessing} onChange={event => setInput(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey && !event.nativeEvent.isComposing) { event.preventDefault(); submit(); } }} placeholder={text.typeMessage} aria-label={text.typeMessage} className="min-h-14 flex-1 resize-none rounded-2xl border border-white/10 bg-white/5 px-4 py-4 outline-none focus:border-[#D7FB69]/50 disabled:opacity-50"/><button type="button" disabled={!input.trim() || isProcessing} onClick={submit} aria-label={text.sendAria} className="grid size-14 place-items-center rounded-2xl bg-[#D7FB69] text-[#17200f] disabled:opacity-40"><Send/></button></div></footer></main>;
}
