import { ArrowLeft, MessageCircle, Mic, Sparkles } from "lucide-react";
import MorrowLogo from "../../components/branding/MorrowLogo";
import { useDevice } from "../../context/DeviceContext";
import { useLanguage } from "../../context/LanguageContext";
import { noriCopy } from "./noriCopy";

export default function NoriModeSelection({ onBack, onChat, onVoice }: { onBack: () => void; onChat: () => void; onVoice: () => void }) {
  const { language, direction } = useLanguage(); const { config } = useDevice(); const text = noriCopy[language];
  const modes = [{ id: "chat", icon: MessageCircle, title: text.chat, description: text.chatDescription, action: text.startChat, onClick: onChat }, ...(config?.settings.voiceAssistantEnabled === false ? [] : [{ id: "voice", icon: Mic, title: text.voice, description: text.voiceDescription, action: text.startVoice, onClick: onVoice }])];
  return <main dir={direction} className="min-h-[100dvh] bg-[#F8F9FA] px-5 py-7 text-[#1F1F1F] sm:px-10"><div className="mx-auto flex min-h-[calc(100dvh-3.5rem)] max-w-3xl flex-col"><header className="flex items-center justify-between"><button type="button" onClick={onBack} aria-label={text.back} className="grid size-12 place-items-center rounded-xl border border-[#ECECEC] bg-white text-[#1F1F1F] shadow-sm transition hover:-translate-y-0.5 hover:shadow-md active:scale-[.98] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#C41E19]/10"><ArrowLeft/></button><MorrowLogo variant="symbol" className="size-12 object-contain" alt="MORROW logo" /></header><section className="my-auto py-8 text-center"><div className="mx-auto grid size-16 place-items-center rounded-2xl border border-[#C41E19]/20 bg-[#C41E19]/5 text-[#C41E19]"><Sparkles/></div><p className="mt-4 text-sm font-bold text-[#C41E19]">NORI AI</p><h1 className="mx-auto mt-3 max-w-2xl text-[clamp(2.2rem,6vw,4.3rem)] font-bold leading-tight tracking-[-.055em] text-[#1F1F1F]">{text.title}</h1><p className="mx-auto mt-4 max-w-xl text-lg text-[#6B7280]">{text.description}</p><div className={`mt-10 grid gap-4 ${modes.length > 1 ? "sm:grid-cols-2" : "mx-auto max-w-md"}`}>{modes.map(({ id, icon: Icon, title, description, action, onClick }) => <article key={id} className="flex min-h-72 flex-col rounded-2xl border border-[#ECECEC] bg-white p-6 text-start shadow-[0_4px_18px_rgba(31,31,31,.06)] transition duration-200 hover:-translate-y-1 hover:shadow-[0_12px_30px_rgba(31,31,31,.1)]"><span className="grid size-16 place-items-center rounded-2xl bg-[#C41E19]/8 text-[#C41E19]"><Icon size={30}/></span><h2 className="mt-6 text-2xl font-bold text-[#1F1F1F]">{title}</h2><p className="mt-2 leading-6 text-[#6B7280]">{description}</p><button type="button" onClick={onClick} aria-label={`${action} Nori`} className="mt-auto min-h-14 rounded-xl bg-[#C41E19] px-5 font-bold text-white shadow-sm transition hover:bg-[#A8161A] hover:shadow-md active:scale-[.98] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#C41E19]/15">{action}</button></article>)}</div></section></div></main>;
}
